const titleSpecials = [
    // [検索パターン, ...ヒットさせたい読み] 曲名頭以外で他曲の構成要素になりそうな場合第二引数をtrue
    // Leet系
    ['ΕΛΠΙΣ','ELPIS','えるぴす'],
    ['FiZZλ_PØT!0И','FIZZY_POTION','ふぃじーぽーしょん','ふぃずぃーぽーしょん'],
    ['CODE:Ø','CODE:0','こーどぜろ'],
    ['ACTØ','ACT0','あくとぜろ'],
    ['3y3s','eyes','あいず'],
    ['M4K3 1T B0UNC3','MAKE IT BOUNCE','めいくいっとばうんす'],
    ['#MAGiCVLGiRL_TRVP_B3VTZ','MAGICALGIRL_TRAP_BEATZ','まじかるがーるとらっぷびーつ'],
    ['Miracle 5ympho X','Miracle Sympho X','みらくるしんふぉえっくす'],
    ['3!dolon Forc3','Eidolon Force','えいどろんふぉーす'],
    ['3V0','EVO','えヴぉ'],
    ['SµG@R RU$#','SUGAR RUSH','しゅがーらっしゅ'],
    ['Τέλος','Telos','てろす'],
    ['Xb10r','Xblor','てんぶらー'],
    ['dAuntl3ss','dauntless','どーんとれす'],
    ['COSMIC V3LOCITY', 'COSMIC VELOCITY', 'こずみっくヴぇろしてぃ'],
    ['Space Battleship S4TØ','Space Battleship SATO','すぺーすばとるしっぷさとー'],

    // 変換面倒
    ['旋律のドグマ～Misérables～','せんりつのどぐまみぜらぶる'],
    ['刃図羅','ばずら','ラストアーツ'],
    ['天空脳番長危機十六連打','てくのばんちょうききじゅうろくれんだ'],
    ['天邪鬼','あまのじゃく'],
    ['口カラ凸ゲキ','くちからとつげき'],
    ['流桜ノ門','るおうのもん'],
    ['烽火連天の刃','ほうかれんてんのやいば'],
    ['色を喪った街','いろをうしなったまち'],
    ['神謳 -RESONANCE-','しんおう'],
    ['爆ぜりゃんせ','はぜりゃんせ'],
    ['逆月','さかづき'],
    ['禊','みそぎ'],
    ['禍根','かこん'],
    ['泰東ノ翠霞','たいとうのすいか'],
    ['泰東ノ翠霞(譜面変更前)','たいとうのすいかふめんへんこうまえ'],
    ['〆','しめ'],
    ['龍王の霊廟(Mausoleum Of The Primal Dragon)','りゅうおうのれいびょうまうそれうむおぶざぷらいまるどらごん'],
    ['終焔のClaudia','しゅうえんのくらうでぃあ'],
    ['零 - ZERO -','ぜろ'],
    ['⁽⁽ଘ( ˙꒳˙ )ଓ⁾⁾ beyond reason','Flying beyond reason','ふらいんぐびよんどりーずん'],

    // 変換面倒外語
    ['ECHIDNA','えちだな','えきどな'],
    ['IX','あいえっくす','ないん','ブラッドメタル'],    
    ['Aegis','あえぎす','いーじす'],
    ['ÆTHER','ATHER','えーてる'],
    ['Fascination MAXX','ふぁっしねーしょんまっくす'],
    ['eRAseRmOToRpHAntOM','えれふぁんとぱおーん','いれーさーもーたーふぁんとむ'],

    // 出れば便利
    ['A','えーす'],
    ['AA','だぶるえーす'],
    ['少年A','しょうねんえーす'],
    ['R∞tAge','るーてーじ','るーていじ'],
    ['NΦ CRIME','のーくらいむ'],
    ['XHRONOXAPSULΞ','くろのかぷせる'],
    ['THE F∀UST','ざふぁうすと'],
    ['Amor∞Fati','Amor Fati','あもーるふぁてぃ'],
    ['smooooch・∀・','すむーち','キャンディレイヴ'],
    ['smooooch・∀・ (Snail\'s House Remix)','すむーちすねいるずはうすりみっくす'],
    ['Wuv U','わヴゆー','キャンディレイヴ'],
    ['Bahram Attack-猫叉Master Remix-','ばふらむあたっくねこまたますたーりみっくす'],
    ['Scripted Connection⇒ A mix','すくりぷてっどこねくしょんえーみっくす'],
    ['Scripted Connection⇒ H mix','すくりぷてっどこねくしょんえいちみっくす'],
    ['Scripted Connection⇒ N mix','すくりぷてっどこねくしょんえぬみっくす'],
    ['Ignis†Iræ','いぐにすいれー','神'],
    ['Saturn','さたーん','さたん'],
    ['冥','めい','ヒューマンシーケンサー'],
    ['卑弥呼','ひみこ'],
    ['弾幕信仰','だんまくしんこう'],
    ['摩天楼','まてんろう'],
    ['最小三倍完全数','さいしょうさんばいかんぜんすう','ひゃくにじゅういちのまえ','ピタゴラス的不完全性破壊衝動音律(ハンマーによる)'],
    ['月光','げっこう'],
    ['東京神話','とうきょうしんわ'],
    ['桜','さくら'],
    ['楽園追放','らくえんついほう'],
    ['次葉 -turn the page-','じようたーんざぺーじ'],
    ['焔極OVERKILL','えんきょくおーばーきる'],
    ['疾風迅雷','しっぷうじんらい'],
    ['真 地獄超特急 -HELL or HELL-','しんじごくちょうとっきゅうへるおあへる'],
    ['童話回廊','どうわかいろう'],
    ['紅牡丹','べにぼたん'],
    ['翼','つばさ'],
    ['華蝶風雪','かちょうふうせつ'],
    ['走馬灯 -The Last Song-','そうまとうざらすとそんぐ'],
    ['鉄甲乙女-under the steel-','てっこうおとめあんだーざすちーる'],
    ['陽炎','かげろう'],
    ['雪月花','せつげっか'],
    ['電光','でんこう'],
    ['電腦都市','でんのうとし'],
    ['革命','かくめい'],
    ['響花水月','きょうかすいげつ'],
    ['鴉','からす'],
    ['大桟橋','おおさんばし'],
    ['新宝島','しんたからじま'],
    ['紫陽花 -AZISAI-','あじさい'],
    ['不沈艦CANDY','ふちんかんきゃんでぃ'],
    ['中華急行','ちゅうかきゅうこう'],
    ['惑星鉄道','わくせいてつどう'],
    ['恋する☆宇宙戦争っ！！','こいするうちゅうせんそうっ','ハイブリープ'],
    ['灼熱 Lost Summer Dayz','しゃくねつろすとさまーでいず'],
    ['ALBA -黎明-','あるばれいめい'],
    ['BLUE DRAGON(雷龍RemixIIDX)','ぶるーどらごんらいりゅうりみっくすつーでぃーえっくす'],
    ['Devilz Staircase','でヴぃるずすてあけーす'],
    ['Devilz Sacrifice -贖罪の羊-','でヴぃるずさくりふぁいすしょくざいのひつじ'],
    ['VALKYRIAS -英雄誕生-','ヴぁるきりあすえいゆうたんじょう'],
    ['Mare Nectaris','まれねくたりす','まーれねくたりす'],
    ['Sinus Iridum','さいなすいりどぅむ','しぬすいりどぅむ'],
    ['Todestrieb','とーですとりーぷ','とーでしゅとりーぷ','傲慢'],
    ['lower world','ろわーわーるど'],
    ['Ha･lle･lu･jah','はれるや'],
    ['VIBRΛ','ヴぃぶら','ばいぶら'],
    ['VOLAQUAS','ヴぉるあくあす','ヴぉらきゅあす'],
    ['Vermilion','ヴぁーみりおん'],
    ['Vermillion','ヴぁーみりおん'],
    ['Vermilion Carol','ばーみりおんきゃろる'],
    ['yellow head joe','いえろーへっどじょー','テックトランス'],
    ['STARS☆☆☆(Re-tuned by HΛL) - IIDX EDITION -','STARS Re-tuned by HAL IIDX EDITION','すたーずりちゅーんどばいはるつーでぃーえっくすえでぃしょん'],
    ['CoMAAAAAAA','こまー'],
    ['Zenith','ぜにす'],
    ['ZEИITH','ぜにす'],
    ['Binary Black Hole','ばいなりぶらっくほーる'],
    ['Bow shock!!','ばうしょっく'],
    ['GRAVITON','ぐらヴぃとん'],
    ['GALGALIM','がるがりむ'],
    ['u gotta beat','ゆーごったびーと','ゆーごったーびーと'],
    ['CHRONO DIVER -NORNIR-','くろのだいばーのるにる'],
    ['chrono diver -fragment-','くろのだいばーふらぐめんと'],
    ['Chronos','くろのす'],
    ['Roar of Chronos','ろあーおぶくろのす'],
    ['EX-MASSIVE FIGHTER','いーえっくすまっしぶふぁいたー'],
    ['POLꞰAMAИIA','ぽるかまにあ'],
    ['Flämingo','ふらみんご'],
    ['Mächö Mönky','まっちょもんきー'],
    ['Präludium','ぷれりゅーでぃうむ'],
    ['Pārvatī','ぱーるヴぁてぃ'],
    ['Atröpøs','あとろぽす'],
    ['Devil\'s Gear','でびるずぎあ'],
    ['Demon March','でーもんまーち'],
    ['Arcanos','あるかのす'],
    ['B4U','びーふぉーゆー'],
    ['B4U(BEMANI FOR YOU MIX)','びーふぉーゆーびーまにふぉーゆーみっくす'],
    ['SPEED DEMON','すぴーどでーもん'],
    ['AO-1','えーおーわん','えいおーわん'],
    ['AO-∞','えーおーいんふぃにてぃ','えいおーいんふぃにてぃ'],
    ['《GRANDMASTER》','ぐらんどますたー'],
    ['《ORDERBREAKER》','おーだーぶれいかー'],
    ['Seraph','せらふ'],
    ['Ambivalent Vermilia','あんびばれんとばーみりあ'],
    ['FERMI♡PARADOX','ふぇるみぱらどっくす'],
    ['Double♡♡Loving Heart','だぶるらびんぐはーと'],
    ['Raspberry♡Heart(English version)','らずべりーはーといんぐりっしゅばーじょん'],
    ['LOVE♡SHINE','らぶしゃいん'],
    ['Sweet Sweet♡Magic','すうぃーとすうぃーとらぶまじっく'],
    ['Kick Out 仮面','きっくあうとかめん'],
    ['Punch Love♡仮面','ぱんちらぶかめん'],
    ['beatchic☆仮面～好き、でいさせて～','びーとちっくかめんすきでいさせて','びーとしっくかめんすきでいさせて'],
    ['Volcanic Dragon','ヴぉるかにっくどらごん'],
    ['VØID','ヴぉいど'],
    ['Say YEEEAHH','せいいぇー'],
    ['FIRE FIRE','ファイアファイア','ファイアーファイアー'],
    ['Spica','すぴか'],
    ['tricky trick','とりっきーとりっく'],
    ['TSAR BOMBA','つぁーりぼんば'],
    ['Broken','ぶろーくん'],
    ['Broken Sword','ぶろーくんそーど'],
    ['Holy Snow','ほーりーすのー'],
    ['GRADIUS -FULL SPEED-','ぐらでぃうすふるすぴーど'],
    ['ＰＡＳＴＥＬＩＳＭ','ぱすてりずむ'],
    ['winkle 2 winkle','うぃんくるとぅうぃんくる'],
    ['RAGE feat.H14 of LEONAIR','れいじふぃーちゃりんぐひよおぶりおねあ'],
    ['乱膳の舞姫','らんぜんのまいひめ'],
    ['二人ノ廃城幽踊宴','ふたりのはいじょうゆうとうえん'],
    ['光風霽月','こうふうせいげつ'],
    ['共鳴遊戯の華','きょうめいゆうぎのはな'],
    ['儚き恋の華','はかなきこいのはな'],
    ['儚キ戀ノ幻想譚','はかなきこいのげんそうたん'],
    ['命の標本','いのちのひょうほん'],
    ['嘆きの樹','なげきのき'],
    ['天泣','てんきゅう','そらなき'],
    ['天使のカンタータ -Cantata of Angels-','てんしのかんたーたかんたーたおぶえんじぇる'],
    ['少女アリスと箱庭幻想コンチェルト','しょうじょありすとはこにわげんそうこんちぇると'],
    ['幻想系世界修復少女','げんそうけいせかいしゅうふくしょうじょ','J-ポップ'],
    ['牧神笛吹きて','ぼくしんふえふきて'],
    ['煉獄のエルフェリア','れんごくのえるふぇりあ'],
    ['煉獄コンフィチュール','れんごくこんふぃちゅーる'],
    ['狂水一華','きょうすいいちか'],
    ['生きるよすが','いきるよすが'],
    ['眠りの国のステラ','ねむりのくにのすてら'],
    ['神っぽいな','かみっぽいな'],
    ['神のシナリオ', 'かみのしなりお'],
    ['累乗のカルマ','るいじょうのかるま'],
    ['罪と罰','つみとばつ'],
    ['罪過の聖堂','ざいかのせいどう'],
    ['聖人の塔','せいじんのとう','暴食'],
    ['草原の王女-軌跡を辿って-','そうげんのおうじょきせきをたどって'],
    ['衰色小町メランコリア','すいしょくこまちめらんこりあ'],
    ['高高度降下低高度開傘','こうこうどこうかていこうどかいさん'],
    ['鬼華-修羅の舞-','きっかしゅらのまい'],
    ['鬼言集','きごんしゅう'],
    ['ギョギョっと人魚♨爆婚ブライダル','ぎょぎょっとにんぎょばっこんぶらいだる'],
    ['多極性ニューロンの崩壊による人間の末路','たきょくせいにゅーろんのほうかいによるにんげんのまつろ'],
    ['深淵に捧ぐレクイエム','しんえんにささぐれくいえむ'],
    ['断罪の一花','だんざいのいちか'],
    ['深愛のリグレット','しんあいのりぐれっと'],
    ['水鏡の異界','すいきょうのいかい'],
    ['湘南族 -cannibal coast-','しょうなんぞくかにばるこーすと'],
    ['炸裂！イェーガー電光チョップ！！(JAEGER FINAL ATTACK)', 'さくれついぇーがーでんこうちょっぷいぇーがーふぁいなるあたっく'],
    ['DENJIN AKATSUKINI TAORERU -SF PureAnalogSynth Mix-', 'でんじんあかつきにたおれるえすえふぴゅああなろぐしんすみっくす'], //
    ['電人、暁に斃れる。', 'でんじんあかつきにたおれる'],
    ['電人イェーガーのテーマ(Theme of DENJIN J)', 'でんじんいぇーがーのてーまてーまおぶでんじんじぇー'], //
    ['合体せよ！ストロングイェーガー！！', 'がったいせよすとろんぐいぇーがー'],
    ['Push on Beats!～音ゲの国のeX-ストリーマー～', 'ぷっしゅおんびーつおとげのくにのえくすとりーまー'],
    ['無双','むそう'],
    ['栄冠のカンパネラ','えいかんのかんぱねら'],
    ['夏色のセレナーデ','なついろのせれなーで'],
    ['朝焼けから始まるボクらの小さな旅','あさやけからはじまるぼくらのちいさなたび'],
    ['死神自爆中二妹アイドルももかりん(1歳)','しにがみじばくちゅうにいもうとあいどるももかりんいっさい'],
    ['時空トラベローグ','じくうとらべろーぐ'],
    ['水上の提督(Short mix from \"幻想水滸伝V\")','すいじょうのていとくしょーとみっくすふろむげんそうすいこでんふぁいぶ'],
    ['涙のテ・エストラーニョ・ムーチョ','なみだのてえすとらーにょむーちょ'],
    ['湘南ロンリーMIDNIGHT RAIN','しょうなんろんりーみっどないとれいん'],
    ['恋愛＝精度×認識力','れんあいせいどにんしきりょく'],
    ['ピアノ協奏曲第1番”蠍火” (BlackY Remix)','ぴあのきょうそうきょくだいいちばんさそりびぶらっきーりみっくす','PDM'],
    ['ピアノ独奏無言歌 \"灰燼\"','ぴあのどくそうむごんかかいじん'],
    ['ワルツ第17番 ト短調”大犬のワルツ”','わるつだいじゅうななばんとたんちょうおおいぬのわるつ'],
    ['1001 -ESCAPE-','せんいちえすけーぷ','わんおーおーわんえすけーぷ'],
    ['24h Endurance Race','とぅえんてぃーふぉーあわーえんでゅらんすれーす','にじゅうよじかんたいきゅうれーす'],
    ['op.31 叙情','おーぴーさんじゅういちじょじょう','おーぱすさんじゅういちじょじょう'],
    ['20XX','にせんえっくすえっくす','とぅえんてぃーえっくすえっくす'],
    ['e-motion 2003  -romantic extra-','いーもーしょんにせんさんろまんてぃっくえくすとら'],
    ['BLAZING_LAZER','ぶれいじんぐれーざー'],
    ['BLACK.by X-Cross Fade','ぶらっくばいえっくすくろすふぇーど','ぶらっくばいくろすふぇーど'],
    ['CaptivAte2～覚醒～','きゃぷてぃべーとつーかくせい'],
    ['C-C-C-N-N-N','しーしーしーえぬえぬえぬ'],
    ['DEATH†ZIGOQ ～怒りの高速爆走野郎～','デス地獄','ですじごくいかりのこうそくばくそうやろう'],
    ['DUAL STRIKER','でゅあるすとらいかー'],
    ['EBONY & IVORY','えぼあぼ','えぼにーあんどあいぼりー','ラグタイムチップチューン'],
    ['Elemental Creation','えれめんたるくりえいしょん','えれめんたるくりえーしょん','ハードルネッサンス'],
    ['Evans','えヴぁんす','ハードルネッサンス2'],
    ['JOMANDA','じょまんだ','ハードルネッサンス3'],
    ['FUZIN RIZIN','ふうじんらいじん'],
    ['GHEL NAGARAJA','げるながらじゃ'],
    ['GiGaGaHell','ぎががへる'],
    ['GuNGNiR','ぐんぐにる'],
    ['HAERETICUS','はえれてぃくす'],
    ['JUSTICE/GUILTY feat. Nana Takahashi & 709sec.','じゃすてぃすぎるてぃ'],
    ['kors k\'s How to make OTOGE CORE','こーすけずはうとぅめいくおとげこあ'],
    ['kors k\'s How to make OTOGE CORE 「LONG」','こーすけずはうとぅめいくおとげこあろんぐ'],
    ['kors k\'s Let\'s make an Image Song!','こーすけずれっつめいくあんいめーじそんぐ'],
    ['L.F.O','えるえふおー'],
    ['Ludus In Tenebris','るーどぅすいんてねぶりす'],
    ['Megalara Garuda','めがららがるーだ'],
    ['route 80s','るーとえいてぃーず'],
    ['O/D*20','おーでぃーとぅえんてぃー','おーばーどーざーにじゅっしゅうねんおめでとう'],
    ['ONIGOROSHI','おにごろし'],
    ['Papilio ulysses','ぱぴりおゆりしーず'],
    ['Peaktime Booster','ぴーくたいむぶーすたー'],
    ['Ristaccia','りすたちあ'],
    ['ruin of opals','るいんおぶおーぱるす'],
    ['SCREW // owo // SCREW','すくりゅーすくりゅー'],
    ['SOLID WYVERN','そりっどわいばーん'],
    ['STEEL NEEDLE','すちーるにーどる'],
    ['TIEFSEE','てぃーふぜー'],
    ['Timepiece phase II','たいむぴーすふぇーずつー'],
    ['Timepiece phase II (CN Ver.)','たいむぴーすふぇーずつーしーえぬばーじょん'],
    ['Trill auf G','とりるあうふげー'],
    ['Viridian','ヴぃりじあん'],
    ['Visterhv','ヴぃすたーヴ'],
    ['Vitrum','ヴぃとらむ'],
    ['Y&Co. is dead or alive','わいあんどこーいずでっどおあらいぶ'],
    ['Ypsilon','いぷしろん'],
    ['ZZ','ぜっとぜっと'],
    ['entelecheia','えんてれけいあ'],
    ['gigadelic','ぎがでりっく'],
    ['onslaught','おんすろーと'],
    ['oratio','おらしょ'],
    ['ra\'am','らーむ'],
    ['rommmo','ろも'],
    ['sakura storm','さくらすとーむ'],
    ['tripping contact','とりっぴんぐこんたくと'],
    ['tripping contact(teranoid&MC Natsack Remix)','とりっぴんぐこんたくとてらのいどあんどえむしーなっとさっくりみっくす'],
    ['Tripping Jumping','とりっぴんぐじゃんぴんぐ','とりっぴんじゃんぴん'],
    ['EMOTiON TRiPPER','えもーしょんとりっぱー'],
    ['COSMIC RAY','こずみっくれい'],
    ['-65℃','まいなすろくじゅうごど'],
    ['《PL|RAYER》','PLAYER','PRAYER','ぷれいやー'],
    ['#The_Relentless','ざりれんとれす'],
    ['∀','たーんえーす'],
    ['199024club -Re:BounceKiller-','いちきゅうきゅうぜろにーよんくらぶりばうんすきらー'],
    ['2 Beasts Unchained','つーびーすつあんちぇいんど'],
    ['255','にひゃくごじゅうご','にごご','つーはんどれっどあんどふぃふてぃふぃふてぃ'],
    ['27th style','とぅえんてぃーせぶんすすたいる'],
    ['A MINSTREL ～ ver. short-scape ～','あみんすとれるばーじょんしょーとすけーぷ'],
    ['AA -rebuild-','だぶるえーすりびるど'],
    ['ABSOLUTE EVIL','あぶそりゅーといびる'],
    ['Adularia','あでゅらりあ'],
    ['Aftermath','あふたーます'],
    ['AIR RAID FROM THA UNDAGROUND','えあれいどふろむだあんだぐらうんど'],
    ['AKASHIC BREAK','あかしっくぶれいく'],
    ['ALBIDA','あるびだ'],
    ['ALL MY TURN -このターンに、オレの全てを賭ける-','おーるまいたーんこのたーんにおれのすべてをかける'],
    ['ALL OK!!','おーるおーけー'],
    ['Almagest (HCN Ver.)','あるまげすとえいちしーえぬばーじょん'],
    ['Almagest','あるまげすと',],
    ['ALTERNATOR','おるたねーたー'],
    ['Always We Trust In You','おーるうぇいずうぃーとらすといんゆー'],
    ['Amazing Mirage','あめいじんぐみらーじゅ'],
    ['ANCHOR','あんかー'],
    ['Angel\'s Ladder','えんじぇるずらだー'],
    ['Anisakis -somatic mutation type"Forza"-','あにさきすそーまてぃっくみゅーてーしょんたいぷふぉるつぁ'], //
    ['anthracene','あんとらせん','あんすらせん'],
    ['Antigravity','あんちぐらびてぃ'],
    ['Apocalypse','あぽかりぷす'],
    ['Aqvion','あくびおん'],
    ['Arabian Rave Night','あらびあんれいヴないと'],
    ['Arca','あるか'],
    ['Arkadia','あるかでぃあ'],
    ['Artist','あーてぃすと'],
    ['ASIAN VIRTUAL REALITIES (MELTING TOGETHER IN DAZZLING DARKNESS)','あじあんヴぁーちゃるりありてぃーずめるてぃんぐとぅぎゃざーいんだずりんだーくねす','あじあんヴぁーちゅぁるりありてぃずめるてぃんぐとぅげざーいんだずりんぐだーくねす'],
    ['BAD BOY BASS!!(dj Remo-con MIX)','ばっどぼーいべーすでぃーじぇーりもこんみっくす'],
    ['B.O.D.Y.','ぼでぃ','びーおーでぃーわい'],
    ['Be quiet','びくわ','びーくわいえっと'],
    ['Beat Juggling Mix','びーとじゃぐりんぐみっくす'],
    ['BEAT PRISONER','びーぷり','びーとぷりずなー','音囚人'],
    ['Beat Radiance','びーとれいでぃあんす'],
    ['BIGWAVERS','びっぐうぇいヴぁーず'],
    ['BIGソムタム','びっぐそむたむ'],
    ['Biometrics Warrior','ばいおめとりくすうぉーりあー'],
    ['BLACK or WHITE?','ぶらっくおあほわいと'],
    ['Boomy and The Boost','ぶーみーあんどざぶーすと'],
    ['Bring The Fire','ぶりんぐざふぁいあ'],
    ['BroGamer','ぶろげーまー'],
    ['Burning Flame','ばーにんぐふれいむ'],
    ['CADENZA','かでんつぁ'],
    ['Candy Galy','きゃんでぃぎゃりー'],
    ['Carmina','かるみな'],
    ['Carry Me Away','きゃりーみーあうぇい'],
    ['Catch Our Fire!','きゃっちあわーふぁいあ'],
    ['Caterpillar','きゃたぴらー'],
    ['Chaotoxin','かおときしん'],
    ['cinder','しんだー'],
    ['Colorful Cookie','からふるくっきー'],
    ['concon','こんこん'],
    ['Confiserie','こんふぃずりー'],
    ['CONTRACT','こんとらくと'],
    ['Cosmic Cat','こずみっくきゃっと'],
    ['Cosy Catastrophe','こーじーかたすとろふぃー'],
    ['Cross Fire','くろすふぁいあ'],
    ['CUE CUE RESCUE','きゅーきゅーれすきゅー'],
    ['Cult Invitation','かるといんヴぃてーしょん'],
    ['Dahlia','だりあ'],
    ['Dances with Snow Fairies','雪妖精','だんしずうぃずすのーふぇありーず'],
    ['DARK LEGACY','だーくれがしー'],
    ['DAY DREAM','でいどりーむ'],
    ['DEADHEAT','でっどひーと'],
    ['Despair of ELFERIA','ですぺあーおぶえるふぇりあ'],
    ['destination','ですてぃねいしょん'],
    ['DIAMOND CROSSING','だいくろ','だいあもんどくろっしんぐ'],
    ['dica dica','でぃかでぃか'],
    ['DIVINE JUDGEMENT','でぃヴぁいんじゃっじめんと'],
    ['Do it!! Do it!!','どぅーいっとどぅーいっと'],
    ['DOMINION','どみにおん'],
    ['Don\'t believe the hype','どんとびりーヴざはいぷ'],
    ['Double Dribble','だぶるどりぶる'],
    ['Dr. Chemical & Killing Machine','どくたーけみかるあんどきりんぐましーん'],
    ['Drastic Dramatic','どらすてぃっくどらまてぃっく'],
    ['Drop Syndicate','どろっぷしんじけいと'], //
    ['DropZ-Line-','どろっぷぜっとらいん'],
    ['DRUNK MONKY','どらんくもんきー'],
    ['DUE TOMORROW','でゅーとぅもろー'],
    ['Dynamite','だいなまいと'],
    ['ELECTRIC MASSIVE DIVER','えれくとりっくまっしぶだいヴぁー'],
    ['Elektrick U-Phoria','えれくとりっくゆーふぉりあ'],
    ['EMERALDAS','えめらるだす'],
    ['Empire of Fury','えんぱいあおぶふゅーりー'],
    ['encounter','えんかうんたー'],
    ['EROICA','えろいか'],
    ['EVANESCENT','えヴぁねせんと'],
    ['Everlasting Message','えばらす','えヴぁーらすてぃんぐめっせーじ'],
    ['EYE OF THE HEAVEN','あいおぶざへヴん'],
    ['F','えふ'],
    ['FAKE TIME','ふぇいくたいむ'],
    ['fallen leaves -IIDX edition-','ふぉーるんりーヴすつーでぃーえっくすえでぃしょん','落ち葉'],
    ['FANTASTIC THREE','ふぁんたすてぃっくすりー'],
    ['FEEDING FRENZY','ふぃーでぃんぐふれんじー'],
    ['Feel The Beat','ふぃるび','ふぃーるざびーと'],
    ['Fegrix','ふぇぐりっくす'],
    ['Fire Beat','ふぁいあびーと'],
    ['Flashes','ふらっしーず'],
    ['FlyAway','ふらいあうぇい'],
    ['Flying Castle','ふらいんぐきゃっする'],
    ['four pieces of heaven','4P','ふぉーぴーしーずおぶへヴん'],
    ['frequent','ふりーくえんと'],
    ['Friction[!]Function','ふりくしょんふぁんくしょん'],
    ['G2','じーつー'],
    ['GAMBOL','がんぼる','がむぼーる'],
    ['GAME ON','げーむおん'],
    ['Ganymede','がにめで'],
    ['GENE','じーん'],
    ['Ghost Pulse','ごーすとぱるす'],
    ['glacia','ぐらしあ'],
    ['Glitch N Ride','ぐりっちんらいど'],
    ['Go Ahead!!','ごあへ','ごーあへっど'],
    ['Go Beyond!!','ごびよ','ごーびよんど'],
    ['GO OVER WITH GLARE -ROOTAGE 26-','ごーおーばーうぃずぐれあるーてーじとぅえんてぃーしっくす'],
    ['God Mind','ごっどまいんど'],
    ['Godspeed','ごっどすぴーど'],
    ['Gravigazer','ぐらヴぃげいざー'],
    ['GRID KNIGHT','ぐりない','ぐりっどないと'],
    ['GUILTY','ぎるてぃ'],
    ['HADES','はです'],
    ['HARD BRAIN','はーどぶれいん'],
    ['hard-wired','はーどわいやーど'],
    ['Hat Surprise','はっとさぷらいず'],
    ['Hat Surprise (Season 2)','はっとさぷらいずしーずんつー'],
    ['Hat Surprise (Season 3)','はっとさぷらいずしーずんすりー'],
    ['Here We Go Now','ひあうぃーごーなう'],
    ['Highcharge Divolt','はいちゃーじでぃヴぉると'],
    ['Hollywood Galaxy','はりぎゃら','はりうっどぎゃらくしー'],
    ['Hollywood Galaxy(DJ NAGAI Remix)','はりうっどぎゃらくしーでぃーじぇーながいりみっくす'],
    ['I','あい'],
    ['ICARUS','いかるす','いかろす'],
    ['Illegal Function Call','いりーがるふぁんくしょんこーる'],
    ['Illusionary Waterlily','いりゅーじょなりーうぉーたーりりー'],
    ['Immortal','いもーたる'],
    ['Inferno of Fomalhaut','いんふぇるのおぶふぉーまるはうと'],
    ['Initiation','いにしえーしょん'],
    ['Inner Spirit','いんなーすぴりっと'],
    ['Inner Spirit -GIGA HiTECH MIX-','いんなーすぴりっとぎがはいてっくみっくす'],
    ['innocent revolver','いのせんとりヴぉるヴぁー'],
    ['Innocent Walls','白壁','いのせんとうぉーるず'],
    ['INSOMNIA','いんそむにあ'],
    ['Invitation from Mr.C','いんヴぃてーしょんふろむみすたーしー'],
    ['invoker','いんヴぉーかー'],
    ['KAISER PHOENIX','かいざーふぇにっくす','鳥貴族'],
    ['KAMAITACHI','かまいたち'],
    ['KILL EACH OTHER','きるいーちあざー'],
    ['Konzert V','こんつぇるとぶい'],
    ['Last Dance','らすとだんす'],
    ['Lethal Weapon','りーさるうぇぽん'],
    ['Level 2','れべるつー'],
    ['Level 3','れべるすりー'],
    ['Level 4','れべるふぉー'],
    ['Level 5','れべるふぁいヴ'],
    ['Level One','れべるわん'],
    ['Liberation','りべれーしょん'],
    ['LIGHTNING STRIKES','らいとにんぐすとらいくす'],
    ['Lightspeed','らいとすぴーど'],
    ['Like+it!','らいくいっと'],
    ['Little Little Princess','りとるりとるぷりんせす','パンクオペラ'],
    ['Little Star','りとるすたー'],
    ['LOCUS OF THE TRAVEL','ろーかすおぶざとらべる'],
    ['Lords Of The Roundtable','ろーずおぶざらうんどてーぶる'],
    ['Lost Souls','ろすとそうるず'],
    ['LOST TECHNOLOGIE','ろすとてくのろじー'],
    ['LOUDER ROLLING THUNDER','らうだーろーりんぐさんだー'],
    ['MAD ATTACK','まっどあたっく'],
    ['Marie Antoinette','まりーあんとわねっと'],
    ['MARLIN','まーりん'],
    ['Matt Silver','まっとしるヴぁー'],
    ['MAX 300','まっくすさんびゃく'],
    ['MAX 360','まっくすさんびゃくろくじゅう','まっくすすりーしっくすおー'],
    ['MAXIMUM CHEAT GIRL','まきしまむちーとがーる'],
    ['MEGAERA','めがいら'],
    ['Meissa','めいっさ'],
    ['MENDES','麺','めんです'],
    ['MENTAL MELTDOWN','めんめる','めんたるめるとだうん'],
    ['Mid-Corner (Magic Maker)','みっどこーなーまじっくめいかー'],
    ['Million Dollar','みりおんだらー'],
    ['Monopole.','ものぽーる'],
    ['mosaic','もざいく'],
    ['n/a','えぬえー'],
    ['NEO GENERATOR SEVEN','ねおじぇねれーたーせぶん'],
    ['New Castle Legions','にゅーきゃっするりーじょんず'],
    ['NEW GENERATION -もう、お前しか見えない-','にゅーじぇねれーしょんもうおまえしかみえない'],
    ['Nightmare before oversleep','ないとめあびふぉーおーヴぁーすりーぷ'],
    ['NINJA IS DEAD IIDX ver.','にんじゃいずでっどつーでぃーえっくすばーじょん'],
    ['NNRT','えぬえぬあーるてぃ','嫉妬'],
    ['No Border','のーぼーだー'],
    ['NOIXIA','のいじあ'],
    ['Nothing but Theory','NbT','なっしんぐばっとせおりー'],
    ['NZM','のぞみ','えぬぜっとえむ'],
    ['ONE AND ONLY','わんあんどおんりー'],
    ['One for All','わんふぉーおーる'],
    ['One More Lovely','わんもあらぶりー'],
    ['one or eight','一八','わんおあえいと'],
    ['Out of Control','あうとおぶこんとろーる'],
    ['Override','おーばーらいど'],
    ['Painful Fate','ぺいんふるふぇいと'],
    ['PARADISE LOST','ぱらろす','ぱらだいすろすと'],
    ['PARANOiA ～HADES～','ぱらのいあはです'],
    ['Phoenix','ふぇにっくす'],
    ['Plan 8','ぷらんえいと'],
    ['PLEASE DON\'T GO','ぷりどん','ぷりーずどんとごー'],
    ['Please Welcome Mr.C','ぷりーずうぇるかむみすたーしー'],
    ['Pluto','ぷるーと'],
    ['POSSESSION','ぽぜっしょん'],
    ['Primitive Vibes','ぷりみてぃぶばいぶす'],
    ['Proof of the existence','ぷるーふおぶじいぐじすてんす'],
    ['Purple Perplex','ぱーぷるぱーぷれっくす'],
    ['Quakes','くえいくす'],
    ['rage against usual','れいじあげいんすとゆーじゅある'],
    ['RAIN','れいん'],
    ['Rampage','らんぺーじ'],
    ['Raspberry Railgun','らずべりーれーるがん'],
    ['Rave Cannon','れいぶきゃのん'],
    ['Rave Patroller','れいぶぱとろーらー'],
    ['Rave*it!! Rave*it!!','れいぶいっとれいぶいっと'],
    ['RED ZONE','赤ぞぬ','れっどぞーん'],
    ['Red. by Full Metal Jacket','れっどばいふるめたるじゃけっと'],
    ['Red. by Jack Trance','れっどばいじゃっくとらんす'],
    ['REFLEXES MANIPULATION','りふれくしーずまにぴゅれいしょん'],
    ['Reflux','りふらっくす'],
    ['refrain','りふれいん'],
    ['Resonant','れぞなんと'],
    ['reunion','りゆにおん'],
    ['REVOLVER','りヴぉるヴぁー'],
    ['Satellite Burst','さてらいとばーすと'],
    ['SAY BAY','せいばい'],
    ['SCREAM SQUAD','すくりーむすかっど','すくりーむすくあっど'],
    ['Secrets','しーくれっつ'],
    ['SEITEN NO TERIYAKI','せいてんのてりやき'],
    ['Sense 2007','せんすにせんなな'],
    ['Session 12 -Esther-','せっしょんとぅえるヴえすてる'],
    ['Session 9 -Chronicles-','せっしょんないんくろにくるず'],
    ['Seven Times Four','せヴんたいむずふぉー'],
    ['Shooting Fireball','しゅーてぃんぐふぁいあぼーる'],
    ['Sigmund','しぐむんど'],
    ['Silver Bullet','しるヴぁーばれっと'],
    ['Sirius','しりうす'],
    ['SISYPHUS','しーしゅぽす','ししふぁす'],
    ['Skreaming for Salvation','すくりーみんぐふぉーさるヴぇいしょん','すくりーみんぐふぉーさるべーしょん'],
    ['Sky High','すかいはい'],
    ['Slipstream','すりっぷすとりーむ'],
    ['Smalt #28598F','すまると'],
    ['Smashing Wedge','すまうぇ','すまっしんぐうぇっじ'],
    ['Snake Stick','蛇棒','すねーくすてぃっく','すねいくすてぃっく'],
    ['Snakey Kung-fu','すねいきーかんふー'],
    ['snow storm','すのーすとーむ'],
    ['SOLAR ECLIPSE','そらえく','日食','そーらーえくりぷす'],
    ['SOLID STATE SQUAD','そりっどすてーとすかっど','そりっどすてーとすくあっど'],
    ['SOLID STATE SQUAD -RISEN RELIC REMIX-','LIFE STREAM','そりっどすてーとすかっどらいずんれりっくりみっくす','そりっどすてーとすくあっどりぃずんれりっくりみっくす'],
    ['Sounds Of Summer','さうんずおぶさまー'],
    ['SpaceLand☆TOYBOX','すぺーすらんどといぼっくす'],
    ['SPECIAL SUMMER CAMPAIGN!','SSC','すぺさま','すぺしゃるさまーきゃんぺーん'],
    ['spiral galaxy','すぱぎゃら','すぱいらるぎゃらくしー'],
    ['Spirit of the Beast','すぴりっとおぶざびーすと'],
    ['STARLIGHT DANCEHALL','すたーらいとだんすほーる'],
    ['STAY GOLD','すていごーるど'],
    ['Steel Edge','すちーるえっじ'],
    ['Stereo Beasts','すてれおびーすつ'],
    ['Summerlights(IIDX Edition)','さまーらいつつーでぃーえっくすえでぃしょん'],
    ['Super Freak','すーぱーふりーく'],
    ['Super Rush','すーぱーらっしゅ'],
    ['suspicions','さすぴしょんず'],
    ['Sweet Clapper','すうぃーとくらっぱー'],
    ['Sword of Vengeance','そーどおぶヴぇんじぇんす'],
    ['Symmetry','しんめとりー'],
    ['SYNC-ANTHEM','しんくあんせむ'],
    ['T-REX vs Velociraptor (In the Far east euphoria)','てぃーれっくすぶいえすヴぇろきらぷとるいんざふぁーいーすとゆーふぉりあ'],
    ['TECHNO Style Essentials','てくのすたいるえっせんしゃるず'],
    ['TECHNOPHOBIA','てくのふぉびあ'],
    ['THANK YOU FOR PLAYING','さんきゅーふぉーぷれいんぐ'],
    ['THE BRAVE MUST DIE','ざぶれいヴますとだい'],
    ['THE CANNONBALLER','ざきゃのんぼーらー'],
    ['The Chase','ざちぇいす'],
    ['The Clown of 24stairs','ざくらうんおぶとぅえんてぃーふぉーすてあーず'],
    ['THE DAY OF JUBILATIONS','ざでいおぶじゅびれいしょんず'],
    ['THE DEEP STRIKER','ざでぃーぷすとらいかー'],
    ['The Last Apocalypse','ざらすとあぽかりぷす'],
    ['The Limbo','座鈴棒','ざりんぼー','憤怒'],
    ['The Onlyonez','ざおんりーわんず'],
    ['THE PEERLESS UNDER HEAVEN','天一','ざぴありすあんだーへヴん'],
    ['The Rebellion of Sequencer','ざりべりおんおぶしーけんさー'],
    ['The Sampling Paradise','ざさんぷりんぐぱらだいす','強欲'],
    ['Thor\'s Hammer','とーるずはんまー','とーるはんまー'],
    ['thunder HOUSE NATION Remix','さんだーりみ','さんだーはうすねいしょんりみっくす'],
    ['Thunderbolt','さんだーぼると'],
    ['Time to Air','たいむとぅーえあー'],
    ['TITANS RETURN','てぃたーんずりたーん'],
    ['TOGAKUSHI','とがくし'],
    ['TOMAHAWK','とまほーく'],
    ['TRANOID','とらのいど'],
    ['Triple Cross','とりぷるくろす'],
    ['TRIUMPH','とらいあんふ'],
    ['TROOPERS','とるーぱーず','とぅるーぱーず'],
    ['Twelfth Style','十二式','とぅえるふすすたいる'],
    ['Umbral','あんぶらる'],
    ['Unbelief','あんびりーふ'],
    ['VANESSA','ヴぁねっさ'],
    ['Venom','ヴぇのむ'],
    ['Violet Pulse','ヴぁいおれっとぱるす'],
    ['VOX RUSH','ヴぉっくすらっしゅ'],
    ['VOX UP','ヴぉっくすあっぷ'],
    ['Watch Out Pt.2','うぉっちあうとぱーとつー','わっちあうとぱーとつー'],
    ['Welcome','うぇるかむ'],
    ['WHA','わ'],
    ['Without Heaven','うぃずあうとへヴん'],
    ['WONDER WALKER','わんだーうぉーかー'],
    ['X','てん','えっくす'],
    ['Xerulean','せるりあん'],
    ['Xperanza','えくすぺらんざ','えすぺらんさ'],
    ['YAKSHA','やくしゃ','やしゃ','審判'],
    ['808monkey','やおやもんきー','はちまるはちもんきー'],
    ['お菓子の王国','おかしのおうこく'],
    ['カゴノトリ～弐式～','かごのとりにしき'],
    ['がっつり陰キャ!? 怪盗いいんちょの億劫^^;','がっつりいんきゃかいとういいんちょのおっくう'],
    ['キヤロラ衛星の軌跡','きやろらえいせいのきせき'],
    ['グッバイ宣言','ぐっばいせんげん'],
    ['シムルグの目醒め','しむるぐのめざめ'],
    ['スキッテイエェエエェ!!!!','すきっていえええええ'],
    ['スパークリング☆彡ハイパーチューン！！','すぱーくりんぐはいぱーちゅーん'],
    ['ぞうしょく！？マイデンティティ','ぞうしょくまいでんてぃてぃ'],
    ['それは花火のような恋','それははなびのようなこい'],
    ['トリカゴノ鳳凰','とりかごのほうおう'],
    ['リリーゼと炎龍レーヴァテイン','りりーぜとえんりゅうれーヴぁていん'],
    ['& Intelligence','あんどいんてりじぇんす'],
    ['(This Is Not) The Angels','でぃすいずのっとじえんじぇるず'],
    ['19,November','ないんてぃーのーべんばー'],
    ['1st Samurai','ふぁーすとさむらい'],
    ['2 Be Continued','とぅーびーこんてぃにゅーど'],
    ['2 Player','とぅーぷれいやー'],
    ['2 tribe 4 K','つーとらいぶふぉーけー'],
    ['2 tribe 4 K(譜面変更前)','つーとらいぶふぁーけーふめんへんこうまえ'],
    ['20,November','とぅえんてぃーのーべんばー'],
    ['2002','にせんに'],
    ['24th Century BOY','とぅえんてぃーせんちゅりーぼーい'],
    ['250bpm','にひゃくごじゅうびーぴーえむ'],
    ['2hot2eat','とぅーほっととぅーいーと'],
    ['3y3s(Long ver.)','あいずろんぐばーじょん'],
    ['5.1.1.','ごーいちいち','ごいちいち'],
    ['5.8.8.','ごーはちはち','ごはちはち'],
    ['50th Memorial Songs -Beginning Story-','ふぃふてぃーすめもりあるそんぐびぎにんぐすとーりー'],
    ['50th Memorial Songs -Flagship medley-','ふぃふてぃーすめもりあるそんぐふらっぐしっぷめどれー'],
    ['50th Memorial Songs -The BEMANI History-','ふぃふてぃーすめもりあるそんぐざびーまにひすとりー'],
    ['50th Memorial Songs -二人の時 ～under the cherry blossoms～-','ふぃふてぃーすめもりあるそんぐふたりのときあんだーざちぇりーぶろっさむず'],
    ['5PM ETERNAL','ふぁいぶぴーえむえたーなる'],
    ['80\'s CAPSULE','えいてぃーずかぷせる'],
    ['8bit Princess','えいとびっとぷりんせす'],
    ['A Certified Rave Moment','あさーてぃふぁいどれいヴもーめんと'],
    ['A Tale Hidden In The Abyss','あているひどぅんいんじあびす'],
    ['A-JAX (3-WAY MIX)','えーじゃっくすすりーうぇいみっくす'],
    ['ABSOLUTE','あぶそりゅーと'],
    ['ABSOLUTE (kors k Remix)','あぶそりゅーとこーすけりみっくす'],
    ['ACCELERATE','あくせられーと'],
    ['ACID VISION','あしっどびじょん'],
    ['ACT','あくと'],
    ['ADAMANT','あだまんと'],
    ['ADVANCE','あどばんす'],
    ['ADVANCE(譜面変更前)','あどばんすふめんへんこうまえ'],
    ['AFRO KNUCKLE','あふろなっくる'],
    ['AGAiN','あげいん'],
    ['AGEHA','あげは'],
    ['AGETEKE ONDO','あげてけおんど'],
    ['ALIEN TEMPLE','えいりあんてんぷる'],
    ['ALIEN WORLD','えいりあんわーるど'],
    ['ALL I NEED YOUR LOVE','おーるあいにーどゆあらぶ'],
    ['ALL RIGHT','おーるらいと'],
    ['AMICABLE','あみかぶる'],
    ['AMRITA -不滅ノ花-','あむりたふめつのはな'],
    ['ANAGMA','あなぐま'],
    ['ANAGRAMS I to Y','あなぐらむすあいとぅわい'],
    ['ANDROMEDA','あんどろめだ'],
    ['ANDROMEDA II','あんどろめだつー'],
    ['ANEMONE','あねもね'],
    ['ANTHEM LANDING','あんせむらんでぃんぐ'],
    ['ASTRAL VOYAGE','あすとらるヴぉやーじゅ'],
    ['ATOMIC AGE','あとみっくえいじ'],
    ['ATOMIC AGE(譜面変更前)','あとみっくえいじふめんへんこうまえ'],
    ['AVE DE RAPINA','あヴぇでらぴな'],
    ['AWA AWA','あわあわ'],
    ['Abraxas','あぶらくさす'],
    ['Abyss','あびす'],
    ['Abyss -The Heavens Remix-','アビ天','あびすざへぶんずりみっくす'],
    ['Acid Pumper','あしっどぱんぱー'],
    ['Acidiva 303','あしっでぃーヴぁさんまるさん'], //
    ['Advent Infamous','あどべんといんふぁます'],
    ['Aerial Skydive','えありあるすかいだいぶ'],
    ['Aeterna','あえてるな','えてるな'],
    ['Affection','あふぇくしょん'],
    ['Ah Hah Yeah','あーはーいぇー'],
    ['Air Bell','えあべる','えあーべる'],
    ['Akatsuki','あかつき'],
    ['All is Wrecked','おーるいずれっくと'],
    ['Almace','あるまーす'],
    ['Alpheratz','あるふぇらっつ'],
    ['Amabie','あまびえ'],
    ['Ambush Ace','あんぶっしゅえーす'],
    ['Amethyst','あめじすと'],
    ['Amnolys','あむのりす'],
    ['Amor De Verão','あもーるでヴぇらおん'],
    ['And-RoiD','あんどろいど'],
    ['Angels & Demons','えんじぇるずあんどでーもんず'],
    ['Answer','あんさー'],
    ['Arcana','あるかな'],
    ['Ariah','ありあ'],
    ['Around The Galaxy','あらうんどざぎゃらくしー'],
    ['Around The Galaxy(譜面変更前)','あらうんどざぎゃらくしーふめんへんこうまえ'],
    ['Around the Future','あらうんどざふゅーちゃー'],
    ['As You Want','あずゆーうぉんと'],
    ['Ascalon','あすかろん'],
    ['AsiaN distractive','あじあんでぃすとらくてぃヴ'],
    ['Astra Blaze','あすとらぶれいず'],
    ['Astrogazer','あすとろげいざー'],
    ['Attitude','あてぃちゅーど'],
    ['Aublia','おーぶりあ'],
    ['Aurora','おーろら'],
    ['BABY LOVE','べいびーらぶ'],
    ['BALLAD FOR YOU～想いの雨～','ばらーどふぉーゆーおもいのあめ'],
    ['BALLAD THE FEATHERS','ばらーどざふぇざーず'],
    ['BEAUTIFUL ANGEL','びゅーてぃふるえんじぇる'],
    ['BEMANI PRO LEAGUE Theme','びーまにぷろりーぐてーま'],
    ['BLACK JACKAL','ぶらっくじゃっかる'],
    ['BLOCKS','ぶろっくす'],
    ['BLUE MIRAGE','ぶるみら','ぶるーみらーじゅ'],
    ['BLUE STRAGGLER','ぶるーすとらぐらー'],
    ['BLUST OF WIND','ぶらすとおぶうぃんど'],
    ['BOOM BOOM DISCO NIGHT','ぶーむぶーむでぃすこないと'],
    ['BRAINSTORM','ぶれいんすとーむ'],
    ['BRAVE GLOW','ぶれいヴぐろー'],
    ['BRAVE OUT','ぶれいヴあうと'],
    ['BREAK OUT','ぶれいくあうと'],
    ['BREAK OVER','ぶれいくおーヴぁー'],
    ['BREATH','ぶれす'],
    ['BREEDING','ぶりーでぃんぐ'],
    ['BRIDAL FESTIVAL !!!','ぶらいだるふぇすてぃヴぁる'],
    ['BRIGHTNESS DARKNESS','ぶらいとねすだーくねす'],
    ['BRILLIANT 2U','ぶりりあんととぅーゆー'],
    ['BRING HER DOWN','ぶりんぐはーだうん'],
    ['BROKEN EDEN','ぶろーくんえでん'],
    ['Back Into The Light','ばっくいんとぅざらいと'],
    ['Back Into The Light -Feeling Won\'t Fade Vocal Mix-','ばっくいんとぅざらいとふぃーりんぐうぉんとふぇーどヴぉーかるみっくす'],
    ['Back Into The Light(CSDD)','ばっくいんとぅざらいとしーえすでぃすとーてっど'],
    ['Back Spin Sweeper','ばっくすぴんすうぃーぱー'],
    ['Back to the Dance Floor','ばっくとぅーざだんすふろあ'],
    ['Backyard Stars','ばっくやーどすたーず'],
    ['Bad Routine','ばっどるーてぃん'],
    ['Bang Bang Dance','ばんばんだんす'],
    ['Bang-Boo Bumble','ばんぶーばんぶる'],
    ['Banger Banger Banger Banger','ばんがーばんがーばんがーばんがー'],
    ['Battle Train -IIDX Edition-','ばとるとれいんつーでぃーえっくすえでぃしょん'],
    ['BattleRoyal','ばとるろいやる'],
    ['Battleground','ばとるぐらうんど'],
    ['Be A Star','びーあすたー'],
    ['Be OK','びーおーけー'],
    ['Be Rock U (1998 burst style)','びーろっくゆーいちきゅうきゅうはちばーすとすたいる'],
    ['Be a Hero!','びーあひーろー'],
    ['Beast mode','びーすともーど'],
    ['Beastie Starter','びーすてぃーすたーたー'],
    ['Beautiful Harmony (IIDX Mix)','びゅーてぃふるはーもにーつーでぃーえっくすみっくす'],
    ['Begin','びぎん'],
    ['Beginning of life(THE GROUND PULSE MIX)','びぎにんぐおぶらいふざぐらうんどぱるすみっくす'],
    ['Believe In Me','びりーヴいんみー'],
    ['Believe in you','びりーヴいんゆー'],
    ['Best of Me','べすとおぶみー'],
    ['Beyond The Seven','びよんどざせヴん'],
    ['BitRacer','びっとれーさー','FMジャジーテック'],
    ['Bitter & Lucky','びたーあんどらっきー'],
    ['Black Apple','ぶらっくあっぷる'],
    ['Blame','ぶれいむ'],
    ['Blaze it UP!','ぶれいずいっとあっぷ'],
    ['Bleeding Luv ～Immorality act～','ぶりーでぃんぐらヴいもらりてぃーあくと'],
    ['Bling-Bang-Bang-Born','ぶりんばんばんぼーん','ぶりんばんばんぼん'],
    ['Bloody Tears(IIDX EDITION)','ぶらっでぃーてぃあーずつーでぃーえっくすえでぃしょん'],
    ['Blown My Heart Away','ぶろーんまいはーとあうぇい'],
    ['Blue Rain','青雨','ぶるーれいん'],
    ['Blue Spring Express','ぶるーすぷりんぐえくすぷれす'],
    ['Blueberry Stream','ぶるーべりーすとりーむ'],
    ['Bounce Bounce Bounce','ばうんすばうんすばうんす'],
    ['Boundary','ばうんだりー'],
    ['Brahma','ぶらーま'],
    ['Brave Spirits','ぶれいヴすぴりっつ'],
    ['Brazilian Fire','ぶらじりあんふぁいあ'],
    ['Break Stasis','ぶれいくすていしす'],
    ['Breakin\' Chain','ぶれいきんちぇいん'],
    ['Breakin\' Rules','ぶれいきんるーるず'],
    ['Breaking the ground','ぶれいきんぐざぐらうんど'],
    ['Broadbanded','ぶろーどばんでっど'],
    ['Broken My Heart','ぶろーくんまいはーと'],
    ['Buffalo','ばっふぁろー'],
    ['Burnin\' The Floor','ばーにんざふろあ'],
    ['Burning Heat! (Full Option Mix)','ばーにんぐひーとふるおぷしょんみっくす'],
    ['Butterfly Twist','ばたふらいついすと'],
    ['CALDERA','かるでら'],
    ['CALL','こーる'],
    ['CAN\'T STOP FALLIN\'IN LOVE','きゃんとすとっぷふぁりんいんらヴ'],
    ['CAR OF YOUR DREAMS','かーおぶゆあどりーむず'],
    ['CARNIVOROUS','かーにヴぉらす'],
    ['CARRY ON NIGHT(English version)','きゃりーおんないといんぐりっしゅばーじょん'],
    ['CELEBRATE NITE','せれぶれいとないと'],
    ['CHAOTIC SUNBIRD','かおてぃっくさんばーど'],
    ['CHARLOTTE','しゃーろっと'],
    ['CHECKING YOU OUT','ちぇっきんぐゆーあうと'],
    ['CHOO CHOO TRAIN (dnb mix)','ちゅーちゅーとれいんどらむんべーすみっくす'],
    ['CLOUDY MUSIC','くらうでぃーみゅーじっく'],
    ['CODE -CRiMSON-','こーどくりむぞん'],
    ['CODE:2','こーどつー'],
    ['COLOR BURST','からーばーすと'],
    ['COLOSSEUM','ころっせうむ'],
    ['CONCEPTUAL','こんせぷちゅある'],
    ['CONNECT-','こねくと'], //
    ['COSMIC CYBER','こずみっくさいばー'],
    ['COSMIC RAISE','こずみっくれいず'],
    ['COSMIC☆WONDER☆REVOLUTION','こずみっくわんだーれヴぉりゅーしょん'],
    ['CROSSROAD','くろすろーどれふとすとーりー','くろすろーどらいとすとーりー'],
    ['CRYMSON','くりむぞん'],
    ['Calvados Queen','かるヴぁどすくいーん'],
    ['Cansei de S NIK','かんせいでえすにっく'],
    ['CaptivAte～浄化～','きゃぷちヴぇいとじょうか','きゃぷてぃヴぇいとじょうか'],
    ['CaptivAte～裁き～','きゃぷちヴぇいとさばき','きゃぷてぃヴぇいとさばき'],
    ['CaptivAte～裁き～(SUBLIME TECHNO MIX)','きゃぷちヴぇいとさばきさぶらいむてくのみっくす','きゃぷてぃヴぇいとさばきさぶらいむてくのみっくす'],
    ['CaptivAte～誓い～','きゃぷちヴぇいとちかい','きゃぷてぃヴぇいとちかい'],
    ['Caramel Pain','きゃらめるぺいん'],
    ['Castle on the Moon','きゃっするおんざむーん'],
    ['Catch Me','きゃっちみー'],
    ['Catch ya Getcha!','きゃっちやげっちゃ','けちゃげっちゃ'],
    ['Central Station','せんとらるすてーしょん'],
    ['Chain of pain','ちぇいんおぶぺいん'],
    ['Change Yourself','ちぇんじゆあせるふ'],
    ['Change the World','ちぇんじざわーるど'],
    ['Changes','ちぇんじず'],
    ['Cheer Train','ちあとれ','ちあーとれいん'],
    ['Chemical Colours','けみかるからーず'],
    ['Chemical Cookie','けみかるくっきー'],
    ['Chewingood!!!','ちゅーいんぐっど'],
    ['Chocolate Dancing','ちょこれーとだんしんぐ'],
    ['Chocolate Planet','ちょこれーとぷらねっと'],
    ['City Never Sleeps (IIDX Edition)','してぃーねヴぁーすりーぷすつーでぃーえっくすえでぃしょん'],
    ['Click Again','くりっくあげいん'],
    ['Clione','くりおね'],
    ['Clione (Ryu☆ Remix)','くりおねりゅーりみっくす'],
    ['Close my Eyes for Me','くろーずまいあいずふぉーみー'],
    ['Cold Moon','こーるどむーん'],
    ['Cold Pulse','こーるどぱるす'],
    ['Colors -Y&Co. Eurobeat Remix-','からーずわいあんどこーゆーろびーとりみっくす'],
    ['Come On','かもーん'],
    ['Comment te dire adieu','こもんとでぃーるあでゅー'],
    ['Constellation','こんすてれいしょん'],
    ['Cookie Bouquets','くっきーぶーけっつ'],
    ['Countdown to Heaven or Hell','かうんとだうんとぅーへヴんおあへる'],
    ['Cradle','くれいどる'],
    ['Crank It','くらんくいっと'],
    ['Crazy Jackpot','くれいじーじゃっくぽっと'],
    ['Crazy K.I.N.O.','くれいじーきの'],
    ['Critical Crystal','くりてぃかるくりすたる'],
    ['Cyber Force','さいばーふぉーす'],
    ['Cyber Force -DJ Yoshitaka Remix-','さいばーふぉーすでぃーじぇいよしたかりみっくす'],
    ['Cyber True Color','さいばーとぅるーからー'],
    ['CyberConnect','さいばーこねくと'],
    ['D','でぃー'],
    ['D.A.N.C.E.!','だんす'],
    ['D.C.fish','でぃーしーふぃっしゅ'],
    ['D2R','でぃーつーあーる'],
    ['DANCER','だんさー'],
    ['DAWN -THE NEXT ENDEAVOUR-','どーんざねくすとえんでヴぁー'],
    ['DAYDREAMER','でいどりーまー'],
    ['DAZZLE ATTACK','だずるあたっく'],
    ['DEEP ROAR','でぃーぷろあー'],
    ['DEEP ROAR(譜面変更前)','でぃーぷろあーふめんへんこうまえ'],
    ['DENIM','でにむ'],
    ['DESIRE','でざいあ'],
    ['DESTINY','ですてぃにー'],
    ['DIAMOND JACKAL','だいあもんどじゃっかる'],
    ['DISPARATE','でぃすぱれーと'],
    ['DIVE ～INTO YOUR HEART～','だいヴいんとゆあはーと'],
    ['DM STAR～関西 energy style～','でぃーえむすたーかんさいえなじーすたいる'],
    ['DO-IT-AMA-SITE!!!','どーいたしまして'],
    ['DON\'T WAKE ME FROM THE DREAM (2010 Summer Edition)','どんとうぇいくみーふろむざどりーむにせんじゅうさまーえでぃしょん'],
    ['DREAM OF SPACE UFO ABDUCTION','どりーむおぶすぺーすゆーふぉーあぶだくしょん'],
    ['DROP','どろっぷ'],
    ['DXY!','溺死','できし','でぃくし','でぃきし'],
    ['DYNAMITE RAVE','だいなまいとれいヴ'],
    ['Damage Per Second','だめーじぱーせこんど'],
    ['Dancin\' Into The Night','だんしんいんとざないと'],
    ['Danza Aestas','だんつぁえすたす'],
    ['Dark Fall','だーくふぉーる'],
    ['Darling my LUV','だーりんぐまいらヴ'],
    ['Dawn Saga','どーんさーが'],
    ['Dazzlin\' Darlin','だずりんだーりん'],
    ['Dazzlin\' Darlin-秋葉工房mix-','だずりんだーりんあきはばらこうぼうみっくす'],
    ['Debtty Daddy','でってぃーだでぃー','でってぃだでぃ'],
    ['Deceive Your Insight','でぃしーヴゆあいんさいと'],
    ['Deep Sea Mystery','でぃーぷしーみすてりー'],
    ['Derelict Star feat. Ryu*','でれりくとすたーふぃーちゃりんぐりゅー'],
    ['Destiny Lovers','ですてぃにーらヴぁーず'],
    ['Destiny Sword','ですてぃにーそーど'],
    ['Devil\'s Gear','でヴぃるずぎあ'],
    ['Digital Radiance','でじたるれいでぃあんす'],
    ['Digital MinD(A/T Libra mix)','でじたるまいんどえーてぃーりぶらみっくす'],
    ['Digital Skipper','でじたるすきっぱー'],
    ['Digitank System','でじたんくしすてむ'],
    ['Discloze','でぃすくろーず'],
    ['Disco Killer Music Lover','でぃすこきらーみゅーじっくらヴぁー'],
    ['Distress','でぃすとれす'],
    ['Divine Heaven','でぃヴぁいんへヴん'],
    ['Do Back Burn','どぅーばっくばーん'],
    ['Do Back Burn(譜面変更前)','どぅーばっくばーんふめんへんこうまえ'],
    ['Do What You Want','どぅほわっとゆーうぉんと'],
    ['DoLL','どーる'],
    ['Don\'t Stop!','どんとすとっぷ'],
    ['Don\'t be afraid myself','どんとびーあふれいどまいせるふ'],
    ['Don\'t believe the hype','どんとびりーヴざはいぷ'],
    ['Don\'t forget','どんとふぉーげっと'],
    ['Don\'t let it go','どれりご','どんとれっといっとごー'],
    ['Donkey Donk','どんきーどんく'],
    ['Dr.LOVE','どくたーらヴ'],
    ['Dreamin Train','どりーみんとれいん'],
    ['Dreamin\' Sun','どりーみんさん'],
    ['Dreaming Dream','どりーみんぐどりーむ'],
    ['Dreaming Sweetness','どりーみんぐすうぃーとねす'],
    ['Dreamship','どりーむしっぷ'],
    ['Drive Me Crazy','どらいヴみーくれいじー'],
    ['Driver','どらいヴぁー'],
    ['Drivin\'','どらいヴぃん'],
    ['Drop It','どろっぷいっと'],
    ['Drop on the floor','どろっぷおんざふろあ'],
    ['Duration','でゅれいしょん'],
    ['Dynasty','だいなすてぃ'],
    ['ECHOES','えこーず'],
    ['EDEN','えでん'],
    ['ELYSIUM','えりじうむ'],
    ['EMPTY OF THE SKY','えんぷてぃおぶざすかい'],
    ['END OF THE CENTURY','えんどおぶざせんちゅりー'],
    ['ERaSeR EnGinE DistorteD','いれいさーえんじんでぃすとーてっど'],
    ['EURO-ROMANCE','ゆーろまんす'],
    ['EVO66','いーヴぃーおーしっくすてぃーしっくす'],
    ['EXCITE','えきさいと'],
    ['EXE','えぐぜ'],
    ['EXODUS SIGN','えくそだすさいん'],
    ['EXTREMA PT.2','えくすとりーまぱーとつー'],
    ['EZ DO DANCE','いーじーどぅーだんす'],
    ['Echo Of Forever','えこーおぶふぉーえヴぁー'],
    ['Echoes of Sunfall','えこーずおぶさんふぉーる'],
    ['Egret and Willow','いーぐれっとあんどうぃろう'],
    ['Eleanor','えりなー','えれのあ'], //
    ['Electric Super Highway','えれくとりっくすーぱーはいうぇい'],
    ['Electrified','えれくとりふぁいど'],
    ['Electrorgasm','えれくとろーがずむ'],
    ['Elisha','えりしゃ'],
    ['Ember Lights','えんばーらいつ'],
    ['Emera','えめら'],
    ['Empire State Glory','えんぱいあすてーとぐろーりー'],
    ['Endless Summer Story','えんどれすさまーすとーりー'],
    ['Energy Drive','えなじーどらいヴ'],
    ['Enjoy your life','えんじょいゆあらいふ'],
    ['ErAseRmoToR maXimUM','いれいさーもーたーまきしまむ'],
    ['Eternal Tears','えたーなるてぃあーず'],
    ['Euphoric Lagoon','ゆーふぉりっくらぐーん'],
    ['Everlasting Last','えヴぁーらすてぃんぐらすと'],
    ['Everlasting Resort','えヴぁーらすてぃんぐりぞーと'],
    ['Exchange Place','えくすちぇんじぷれいす'],
    ['Exhaust Hype','えぐぞーすとはいぷ','いぐぞーすとはいぷ'],
    ['Expanded !!','えくすぱんでっど'],
    ['Explorer feat. ぷにぷに電機','えくすぷろーらふぃーちゃりんぐぷにぷにでんき'],
    ['Express Emotion','えくすぷれすえもーしょん'],
    ['FAKE STYLE II','ふぇいくすたいるつー'],
    ['FEEL IT','ふぃーるいっと'],
    ['FESTA DO SOL','ふぇすたどぅそる'],
    ['FINALLY BLAZE','ふぁいなりーぶれいず'],
    ['FIRE BALL','ふぁいあぼーる'],
    ['FLAG OF PEACE','ふらっぐおぶぴーす'],
    ['FLUTE MAN','ふるーとまん'],
    ['FREEDOM','ふりーだむ'],
    ['FUNKTION','ふぁんくしょん'],
    ['FUTURE is Dead','ふゅーちゃーいずでっど'],
    ['Fading Stars','ふぇいでぃんぐすたーず'],
    ['Fantasia','ふぁんたじあ','ハイパーファンタジア'],
    ['Fantastic Merry-Go-Round','ふぁんたすてぃっくめりーごーらうんど'],
    ['Farewell to Marrakech','ふぇあうぇるとぅまらけしゅ'],
    ['Fashion Fruit','ふぁっしょんふるーつ'],
    ['Feedback','ふぃーどばっく'],
    ['Fervidex','ふぇるヴぃでっくす'],
    ['Fiery Stallion','ふぁいありーすたりおん'],
    ['Final Count Down(MTO CRY BABY STYLE)','ふぁいなるかうんとだうんえむてぃおーくらいべいびーすたいる'],
    ['First Resolution','ふぁーすとれぞりゅーしょん'],
    ['Five Regrets','ふぁいヴりぐれっつ'],
    ['Flash Back 90\'s','ふらっしゅばっくないんてぃーず'],
    ['Flip Flap','ふりっぷふらっぷ'],
    ['Fly Above','あぼべ','ふらいあばーぶ','ふらいあぼーヴ'],
    ['Fly Above (Vicissitude Remix)','ふらいあばーヴヴぃしすちゅーどりみっくす','ふらいあぼーヴヴぃしすちゅーどりみっくす'],
    ['Fly Away To India','ふらいあうぇいとぅーいんでぃあ'],
    ['Fly you to the star','ふらいゆーとぅーざすたー'],
    ['Follow Tomorrow','ふぉろーとぅもろー'],
    ['Forgetting Machine','ふぉーげってぃんぐましーん'],
    ['Fractal','ふらくたる'],
    ['Free Style','ふりーすたいる'],
    ['Freeway Shuffle','ふりーうぇいしゃっふる'],
    ['Freezing atmosphere','ふりーじんぐあともすふぃあ'],
    ['Frisk And Squeak','ふりすくあんどすくぃーく'],
    ['From Human Blood','ふろむひゅーまんぶらっど'],
    ['From Time To Time','ふろむたいむとぅーたいむ'],
    ['Frozen Ray (original mix)','ふろーずんれいおりじなるみっくす'],
    ['Funny shuffle','ふぁにーしゃっふる'],
    ['GENOCIDE','じぇのさいど'],
    ['GENOM SCREAMS','げのむすくりーむず'],
    ['GET ON BEAT(WILD STYLE)','げっとおんびーとわいるどすたいる'],
    ['GET READY!!','げっとれでぃー'],
    ['GET UP AGAIN','げっとあっぷあげいん'],
    ['GHOST','ごーすと'],
    ['GHOST REVIVAL','ごーすとりヴぁいヴぁる'],
    ['GHOSTBUSTERS','ごーすとばすたーず'],
    ['GIGA RAID','ぎがれいど'],
    ['GIGA THRASH','ぎがすらっしゅ'],
    ['GIGA VIOLATE','ぎがヴぁいおれいと'],
    ['GIGANT','ぎがんと'],
    ['GLORIOUS HAMMER','ぐろりあすはんまー'],
    ['GO!','ごー'],
    ['GOBBLE','ごぶる'],
    ['GOLD RUSH 2025','ごーるどらっしゅにせんにじゅうご'],
    ['GRADIUSIC CYBER','ぐらでぃうしっくさいばー'],
    ['GREEN EYES','ぐりーんあいず'],
    ['GRID KNIGHT(譜面変更前)','ぐりっどないとふめんへんこうまえ'],
    ['GROOVE 04','ぐるーヴぜろよん'],
    ['Galaxy Collapse','ぎゃらくしーこらぷす'],
    ['Game Changers','げーむちぇんじゃーず'],
    ['Garuda','がるーだ'],
    ['General Relativity','じぇねらるりれいてぃヴぃてぃー'],
    ['Get Higher','げっとはいあー'],
    ['Get On Your Feet','げっとおんゆあふぃーと'],
    ['Get Out','げっとあうと'],
    ['Get Wicked','げっとうぃきっど'],
    ['Get\'em up to R.A.V.E','げってむあっぷとぅーれいヴ'],
    ['Gimme a Big Beat','ぎみーあびっぐびーと'],
    ['Giudecca','じゅでっか'],
    ['Give Me A Sign','ぎヴみーあさいん'],
    ['Give Me Your Love','ぎヴみーゆあらヴ'],
    ['Glitch Nerds','ぐりっちなーず'],
    ['Globe Glitter','ぐろーぶぐりったー'],
    ['GloriosA','ぐろりおーさ'],
    ['Glorious Days','ぐろりあすでいず'],
    ['Glory','ぐろーりー'],
    ['Go Berzerk','ぽんですてーん','ごーばーざーく','ごーばーさーく'],
    ['Go Faraway','ごーふぁらうぇい'],
    ['Golden Horn','ごーるでんほーん'],
    ['Golden Palms','ごるぱ','ごーるでんぱーむず'],
    ['Good Looking','ぐっどるっきんぐ'],
    ['Gravity','ぐらヴぃてぃ'],
    ['Guilt & Love','ぎるとあんどらヴ'],
    ['Gymnopedie 009','じむのぺでぃぜろぜろきゅう'],
    ['HALF MOON','はーふむーん'],
    ['HAPPY★RUSH','はっぴーらっしゅ'],
    ['HAPPY☆ANGEL','はっぴーえんじぇる'],
    ['HAPPY☆LUCKY☆YEAPPY','はっぴーらっきーいぇっぴー'],
    ['HARMONY','はーもにー'],
    ['HAT TRICK','はっととりっく'],
    ['HEARTACHE','はーとえいく'],
    ['HEARTBEAT','はーとびーと'],
    ['HEISEI','へいせい'],
    ['HELL SCAPER -Last Escape Remix-','へるすけいぱーらすとえすけいぷりみっくす'],
    ['HEROES','ひーろーず'],
    ['HI SCHOOL DREAM','はいすくーるどりーむ'],
    ['HIGH','はい'],
    ['HIGH VOLTAGE','はいヴぉるてーじ'],
    ['HONEY♂PUNCH','はにーぱんち'],
    ['HONEY♂PUNCH～L.E.D.-G STYLE MIX～','はにーぱんちえるいーでぃーじーすたいるみっくす'],
    ['HORIZON','ほらいぞん'],
    ['HORIZON BEATZ','ほらいぞんびーつ'],
    ['HOT LIMIT','ほっとりみっと'],
    ['HOUSE NATION','はうすねいしょん'],
    ['HYPE THE CORE','はいぷざこあ'],
    ['HYPE THE CORE(譜面変更前)','はいぷざこあふめんへんこうまえ'],
    ['HYPER BOUNDARY GATE','はいぱーばうんだりーげーと'],
    ['HYPER EUROBEAT (2DX style)','はいぱーゆーろびーとつーでぃーえっくすすたいる'],
    ['HYPERION','はいぺりおん'],
    ['Halfway of promise','はーふうぇいおぶぷろみす'],
    ['Hallucination','はるしねいしょん'],
    ['Happy Wedding','はぴうぇ','はっぴーうぇでぃんぐ'],
    ['Hard Breaker','はーどぶれいかー'],
    ['Hardcore Mania','はーどこあまにあ'],
    ['Harmony and Lovely','はーもにーあんどらヴりー'],
    ['Heavenly Sun (IIDX VERSION)','へヴんりーさんつーでぃーえっくすばーじょん'],
    ['Hella Deep','へらでぃーぷ'],
    ['Hello Happiness','はろーはぴねす'],
    ['Here We Are','ひあうぃーあー'],
    ['Hitch Hiker','ひっちはいかー'],
    ['Hitch Hiker2','ひっちはいかーつー'],
    ['Hold My Hand','ほーるどまいはんど'],
    ['Holic','ほりっく'],
    ['Honey Trap','はにーとらっぷ'],
    ['Hopeful Daybreak!!!','ほーぷふるでいぶれいく'],
    ['Horizons of Promise','ほらいぞんずおぶぷろみす'],
    ['Hormiga obrera','おるみーがおぶれーら'],
    ['Hurry Hurry','はりーはりー'],
    ['Hybrid Landscape','はいぶりっどらんどすけーぷ'],
    ['Hydrogen Blueback','はいどろげんぶるーばっく','はいどろじぇんぶるーばっく'],
    ['HyperTwist','はいぱーつぃすと'],
    ['Hypersonik','はいぱーそにっく'],
    ['I FIGHT ME','私戦う私','あいふぁいとみー'],
    ['I Love You','あいらヴゆー'],
    ['I Want To Do This Keep','あいうぉんととぅーどぅーでぃすきーぷ'],
    ['I Was The One','あいわずざわん'],
    ['I Was The One (80\'s EUROBEAT STYLE)','あいわずざわんえいてぃーずゆーろびーとすたいる'],
    ['I am','あいあむ'],
    ['I can fly,I\'ve got reason','あいきゃんふらいあいヴごっとりーずん'],
    ['I know You know','あいのーゆーのー'],
    ['I will be back -オレは帰ってきた-','あいうぃるびーばっくおれはかえってきた'],
    ['I\'m Coming (2017 Version)','あいむかみんぐにせんじゅうしちばーじょん'],
    ['I\'m In Love Again -DJ YOSHITAKA REMIX-','あいむいんらヴあげいんでぃーじぇいよしたかりみっくす'],
    ['I\'m In Love Again -Y&Co. EURO MIX-','あいむいんらヴあげいんわいあんどこーゆーろみっくす'],
    ['IDC feat.REVERBEE (Mo\'Cuts Ver)','あいでぃーしーふぃーちゃりんぐりヴぁーびーもーかっつばーじょん'],
    ['IDOL syndrome.','あいどるしんどろーむ'],
    ['IIDX RED Ending (Ryu☆Remix)','つーでぃーえっくすれっどえんでぃんぐりゅーすたーりみっくす'],
    ['ILAYZA','いれいざ'],
    ['ILIAS','いりあす'],
    ['IN BETWEEN','いんびとぅいーん'],
    ['IN THE NAME OF LOVE','いんざねーむおぶらヴ'],
    ['INAZUMA','いなずま'],
    ['INFERNO','いんふぇるの'],
    ['INHERITANCE','いんへりたんす'],
    ['INJECTION OF LOVE','いんじぇくしょんおぶらヴ'],
    ['INORI','いのり'],
    ['INSERTiON','いんさーしょん'],
    ['INVISIBLE STRIX','いんヴぃじぶるすとりっくす'],
    ['IS THIS LOVE?','いずでぃすらぶ'],
    ['IXION','いくしおん'],
    ['IceCube Pf.(RX-Ver.S.P.L.)','あいすきゅーぶぴーえふあーるえっくすばーじょんえすぴーえる'], //
    ['If','いふ'],
    ['In Heaven','いんへヴん'],
    ['In the Blackest Den','いんざぶらっけすとでん','怠惰'],
    ['Indigo Vision(full flavour hide around mix)','いんでぃごヴぃじょんふるふれーヴぁーはいどあらうんどみっくす'],
    ['Infinite cave','いんふぃにっとけいヴ'],
    ['Infinity Mirror','いんふぃにてぃみらー'],
    ['Inside Insight','いんさいどいんさいと'],
    ['Into The Madness','いんとぅーざまっどねす'],
    ['Into The Sunlight','いんとぅーざさんらいと'],
    ['Iris','あいりす'],
    ['JAM','じゃむ'],
    ['JEWELLERY STORM','じゅえりーすとーむ'],
    ['JIVE INTO THE NIGHT','じゃいヴいんとざないと'],
    ['JOURNEY TO "FANTASICA" (IIDX LIMITED )','じゃーにーとぅふぁんたじかつーでぃーえっくすりみてっど'],
    ['Jam&Marmalade','じゃむあんどまーまれーど'],
    ['Jetcoaster Windy','じぇっとこーすたーうぃんでぃ'],
    ['Journey','じゃーにー'],
    ['Jumper','じゃんぱー'],
    ['Jungle Eater','じゃんぐるいーたー'],
    ['Just Gimme','じゃすとぎみー'],
    ['Just a Little Smile','りとすま','じゃすとありとるすまいる'],
    ['KAMIKAZE','かみかぜ'],
    ['KEEP ON MOVIN\'','きーぽん','きーぷおんむーびん'],
    ['KEY','きー'],
    ['KING','きんぐ'],
    ['KING OF GROOVE','きんぐおぶぐるーヴ'],
    ['KI・SE・KI (IIDX RED EDIT)','きせきつーでぃーえっくすれっどえでぃっと'],
    ['KOTONOHA ft. Kotoha','ことのはふぃーちゃりんぐことは'],
    ['KYAMISAMA ONEGAI!','きゃみさまおねがい'],
    ['Kailua','かいるあ'],
    ['Kailua (HCN Ver.)','かいるあえいちしーえぬばーじょん'],
    ['Karma','かるま'],
    ['Kecak','けちゃ'],
    ['Keep it-秋葉工房mix-','きーぷいっとあきはばらこうぼうみっくす'],
    ['King of Tribe','きんぐおぶとらいぶ'],
    ['Kiss me all night long','きすみーおーるないとろんぐ'],
    ['LA FESTA LA VITA!!','らふぇすたらヴぃーた'],
    ['LAB','らぼ','らぶ'],
    ['LADS','らっず'],
    ['LADYBIRD','れでぃーばーど'],
    ['LASER CRUSTER (IGNITE REMIX)','れーざーくらすたーいぐないとりみっくす'],
    ['LAST DAY','らすとでい'],
    ['LEADING CYBER','りーでぃんぐさいばー'],
    ['LEMON MELON COOKIE','れもんめろんくっきー'],
    ['LESSON 5','れっすんふぁいヴ'],
    ['LIFE SCROLLING','らいふすくろーりんぐ'],
    ['LIGHT MOTION','らいともーしょん'],
    ['LIKE A VAMPIRE','らいくあヴぁんぱいあ'],
    ['LIMITED','りみてっど'],
    ['LOVE AGAIN TONIGHT～for Mellisa mix～','らヴあげいんとぅないとふぉーめりさみっくす'],
    ['LOVE B.B.B','らヴびーびーびー'],
    ['LOVE GENERATION','らヴじぇねれーしょん'],
    ['LOVE IS DROWING','らヴいずどろーいんぐ'],
    ['LOVE WILL・・・','らヴうぃる'],
    ['LOVELY STORM','らヴりーすとーむ'],
    ['LOW','ろー'],
    ['LUV CAN SAVE U','らヴきゃんせいヴゆー'],
    ['LUV DRIVE','らヴどらいヴ'],
    ['LUV TO ME (disco mix)','らヴとぅーみーでぃすこみっくす'],
    ['LUV TO ME(UCCHIE\'S EDITION)','らヴとぅーみーうっちーずえでぃしょん'],
    ['La Mar','らまー'],
    ['La dolce primavera','らどるちぇぷりまヴぇーら'],
    ['Last Burning','らすとばーにんぐ'],
    ['Last Card','らすとかーど'],
    ['Last Message','らすとめっせーじ'],
    ['Lawes\'s Parotia','ろーずぱろーしゃ'],
    ['Leaving...','りーヴぃんぐ'],
    ['Leaving...(譜面変更前)','りーヴぃんぐふめんへんこうまえ'],
    ['Legendary Treasures','れじぇんだりーとれじゃーず'],
    ['Les filles balancent','れふぃーゆばらんす'],
    ['Let The Snow Paint Me -Y&Co. Remix-','れっとざすのーぺいんとみーわいあんどこーりみっくす'],
    ['Let The Track Flow','れっとざとらっくふろー'],
    ['Let me be your cure','れっとみーびーゆあきゅあ'],
    ['Let the Snow Paint Me','れっとざすのーぺいんとみー'],
    ['Let\'s Bounce !!','れっつばうんす'],
    ['Let\'s run','れっつらん'],
    ['Let\'s say Hello!','れっつせいはろー'],
    ['Lift Us High','りふとあすはい'],
    ['Light My Fire','らいとまいふぁいあ'],
    ['Light Shine','らいとしゃいん'],
    ['Light and Cyber…','らいさい','らいとあんどさいばー'],
    ['Lighting Shower','らいとにんぐしゃわー','らいてぃんぐしゃわー'],
    ['Line 4 Ruin','らいんふぉーるいん'],
    ['Lisa-RICCIA','りさりしあ'],
    ['Listen up','りっすんあっぷ'],
    ['Logic Board','ろじぼ','ろじっくぼーど'],
    ['London Affairs Beckoned With Money Loved By Yellow Papers.','ろんどんあふぇあーずべかんどうぃずまにーらヴどばいいえろーぺーぱーず'],
    ['Look To The Sky(cyber True Color)','るっくとぅーざすかいさいばーとぅるーからー'],
    ['Lost wing at.0','ろすとうぃんぐあっとぽいんとぜろ'],
    ['Love Again...','らヴあげいん'],
    ['Love Is Eternity','らヴいずえたーにてぃ'],
    ['Love Is Eternity(譜面変更前)','らヴいずえたーにてぃふめんへんこうまえ'],
    ['Love Magic','らヴまじっく'],
    ['Love Me Do','らヴみーどぅー'],
    ['Lovely Howdy Cowboy!!','らヴりーはうでぃーかうぼーい'],
    ['Love♡km','らヴきろめーとる'],
    ['Lucky Days','らっきーでいず'],
    ['Lucy','るーしー'],
    ['Luna Plena','るーなぷれーな'],
    ['Luv 2 Feel Your Body','らぶとぅーふぃーるゆあぼでぃ'],
    ['Lycoris','りこりす'],
    ['M.D.Injection','えむでぃーいんじぇくしょん'],
    ['MAGIC & LOVE','まじっくあんどらヴ'],
    ['MARIA(I believe...)','まりああいびりーヴ'],
    ['MAX 300(譜面変更前)','まっくすさんびゃくふめんへんこうまえ'],
    ['MAX LOVE','まっくすらヴ'],
    ['MAXIVCORD','まきしヴこーど'],
    ['MA・TSU・RI','まつり'],
    ['METALLIC MIND','めたりっくまいんど'],
    ['MINT','みんと'],
    ['MIRACLE MEETS','みらくるみーつ'],
    ['MIRU key way','みるきーうぇい'],
    ['MOCHIMOCHI DREAMIN!!','もちもちどりーみん'],
    ['MOON RACE','むーんれーす'],
    ['MOVE! (We Keep It Movin\')','むーヴうぃきーぷいっとむーヴぃん'],
    ['MUSIC TO YOUR HEAD','みゅーじっくとぅーゆあへっど'],
    ['MVP','えむぶいぴー'],
    ['MY FUTURE','まいふゅーちゃー'],
    ['Macho Gang','まっちょぎゃんぐ'],
    ['Magical','まじかる'],
    ['Make A Difference','めいくあでぃふぁれんす'],
    ['Make A Difference(譜面変更前)','めいくあでぃふぁれんすふめんへんこうまえ'],
    ['Make Me Your Own','めいくみーゆあおうん'],
    ['Makin\' It','めいきんいっと'],
    ['Marmalade Reverie','まーまれーどれヴぇりー'],
    ['Mars beach','まーずびーち'],
    ['Medicine of love','めでぃしんおぶらヴ'],
    ['Mel','める'],
    ['Melody Life','めろでぃらいふ'],
    ['Memoria Obscura','めもりあおぶすきゅら','めもりあおぶすくら'],
    ['Mermaid girl-秋葉工房 MIX-','まーめいどがーるあきばこうぼうみっくす'],
    ['Metagame Matador','めたげーむまたどーる'],
    ['Meteor☆Shower','めておしゃわー'],
    ['Miami Sunset Drive','まいあみさんせっとどらいヴ'],
    ['Midnight Drive','みっどないとどらいヴ'],
    ['Midnight Lady','みっどないとれでぃー'],
    ['Mighty Cutie','まいてぃーきゅーてぃ'],
    ['Mind Mapping','まいんどまっぴんぐ'],
    ['Mira','みら'],
    ['Mobo★Moga','もぼもが'],
    ['Modular Technology','もじゅらーてくのろじー'],
    ['Monkey Business','もんきーびじねす'],
    ['Monkey Dance','もんきーだんす'],
    ['Monkey Dance \'09','もんきーだんすぜろきゅう'],
    ['More Move','もあむーヴ'],
    ['Move Me','むーヴみー'],
    ['Move UR Body','むーヴゆあぼでぃ'],
    ['Moving on','むーヴぃんぐおん'],
    ['Mr.T.(take me higher)','みすたーてぃーていくみーはいあー'],
    ['Mukade','むかで'],
    ['Music is The Answer','みゅーじっくいずじあんさー'],
    ['Musik LoverZ','みゅーじっくらヴぁーず'],
    ['My Only Shining Star','まいおんりーしゃいにんぐすたー'],
    ['My Sweet Bird?','まいすうぃーとばーど'],
    ['Mysterious Time','みすてりあすたいむ'],
    ['NANAIRO','なないろ'],
    ['NEBULA GRASPER','ねびゅらぐらすぱー'],
    ['NEEDLESS MY LOVE FOR YOU','にーどれすまいらヴふぉーゆー'],
    ['NEMESIS','ねめしす'],
    ['NEMESIS -gratitude remix- IIDX Edition','ねめしすぐらてぃちゅーどりみっくすつーでぃーえっくすえでぃしょん'],
    ['NEW SENSATION -もう、あなたしか見えない-','にゅーせんせーしょんもうあなたしかみえない'],
    ['NEWALONE','にゅーあろーん'],
    ['NIGHT FLIGHT TO TOKYO','ないとふらいとぅとうきょう'],
    ['NO DOUBT GET LOUD','のーだうとげっとらうど'],
    ['NO LIMIT -オレ達に限界は無い-','のーりみっとおれたちにげんかいはない'],
    ['NORTH','のーす'],
    ['NPC World','えぬぴーしーわーるど'],
    ['Narcissus At Oasis','なるきっそすあっとおあしす'],
    ['Nasty Techniques','なすてぃてくにーくす'],
    ['Nasty!','なすてぃ'],
    ['Necroxis Girl','ねくろくしすがーる'],
    ['Nemophila','ねもふぃら'],
    ['Neo Heritage','ねおへりてーじ'],
    ['Neonlights','ねおんらいつ'],
    ['Never Fade Away','ねヴぁーふぇいどあうぇい'],
    ['New Castle Legions(譜面変更前)','にゅーきゃっするりーじょんずふめんへんこうまえ'],
    ['New Decade IIDX Edition','にゅーでぃけいどつーでぃーえっくすえでぃしょん'],
    ['New Lights','にゅーらいつ'],
    ['Next Level','ねくすとれヴぇる'],
    ['Next Tales 2 Oath (IIDX 20th Anniv "Ring" Theme)','ねくすとているずとぅーおーすつーでぃーえっくすとぅえんてぃーすあにばーさりーりんぐてーま'],
    ['Night sky','ないとすかい'],
    ['Night! Night! Night!','ないとないとないと'],
    ['No Day But Today!','のーでいばっととぅでい'],
    ['No Tears','のーてぃあず'],
    ['NoN-Fiction Story!','のんふぃくしょんすとーりー'],
    ['Non Stop Rock','のんすとっぷろっく'],
    ['Now and Forever','なうあんどふぉーえヴぁー'],
    ['Nowhere','のーうぇあ'],
    ['Nyan Nyan University','にゃんにゃんゆにヴぁーしてぃ'],
    ['ON THE TUBE','おんざちゅーぶ'],
    ['OOO','おーおーおー'],
    ['ORCA','おるか'],
    ['OTENAMI Hurricane','おてなみはりけーん'],
    ['OTOKOZAKA','おとこざか'],
    ['OUTER LIMITS ALTERNATIVE','あうたーりみっつおるたーねてぃヴ'],
    ['OUTER LIMITS(CSDD)','あうたーりみっつしーえすでぃすとーてっど'],
    ['OUTER PLANETS','あうたーぷらねっつ'],
    ['OVER THE CLOUDS','おーヴぁーざくらうず','ハウス'],
    ['OVER THE CLOUDS -Flying Grind mix-','おーヴぁーざくらうずふらいんぐぐらいんどみっくす'],
    ['OVER TIME','おーヴぁーたいむ'],
    ['OVER VOLTAGE','おーヴぁーヴぉるてーじ'],
    ['Odin','おーでぃん'],
    ['Ohayo!','おはよー'],
    ['On My Wings (HARDSTYLE IIDX)','おんまいうぃんぐすはーどすたいるつーでぃーえっくす'],
    ['On the FM','おんざえふえむ'],
    ['One of A Kind','わんおぶあかいんど'],
    ['Only for now','おんりーふぉーなう'],
    ['Onyx','おにきす'],
    ['Our Song','あわーそんぐ'],
    ['Outbreak','あうとぶれいく'],
    ['Overload Frontier','おーヴぁーろーどふろんてぃあ'],
    ['Overslept','おーヴぁーすれぷと'],
    ['P.O.W.E.R.','ぱわー'],
    ['PALETTE','ぱれっと'],
    ['PAPAYAPA BASS','ぱぱやぱべーす'],
    ['PARANOIA MAX～DIRTY MIX～','ぱらのいあまっくすだーてぃみっくす'],
    ['PARANOIA survivor MAX','ぱらのいあさヴぁいヴぁーまっくす'],
    ['PARANOIA survivor MAX(譜面変更前)','ぱらのいあさヴぁいヴぁーまっくすふめんへんこうまえ'],
    ['PATRIOTISM','ぱとりおてぃずむ'],
    ['PENDUAL TALISMAN','ぺんでゅあるたりすまん'],
    ['PERFECT GREAT!!','ぱーふぇくとぐれいと'],
    ['PERFECT HUMAN','ぱーふぇくとひゅーまん'],
    ['PERFECTWORLD','ぱーふぇくとわーるど'],
    ['PHASE SHIFT MANEUVER','ふぇいずしふとまにゅーヴぁー'],
    ['PHOTONGENIC','ふぉとんじぇにっく'],
    ['PHOTONGENIC(譜面変更前)','ふぉとんじぇにっくふめんへんこうまえ'],
    ['PILGRIM','ぴるぐりむ'],
    ['PIRATES BLADE','ぱいれーつぶれいど'],
    ['PIT A PAT','ぴったぱっと'],
    ['PLASMA','ぷらずま'],
    ['PLATONIC-XXX','ぷらとにっくきす'],
    ['POINT ZERO','ぽいんとぜろ'],
    ['POODLE','ぷーどる'],
    ['POP TEAM EPIC(kors k remix)','ぽぷてぴぴっくこーすけりみっくす','ぽっぷちーむえぴっくこーすけりみっくす'],
    ['POWER DREAM','ぱわーどりーむ'],
    ['PROMISE FOR LIFE','ぷろみすふぁーらいふ'],
    ['PSYCHE PLANET-GT','さいけぷらねっとじーてぃー'],
    ['Pale Garden','ぺいるがーでん'],
    ['Para siempre','ぱらしえんぷれ'],
    ['Parasite World','ぱらさいとわーるど'],
    ['Particle Arts','ぱーてぃくるあーつ'],
    ['Party Starter','ぱーてぃすたーたー'],
    ['Peng-Ging Sky High!!','ぺんぎんすかいはい'],
    ['PentaCube Gt.(RX-Ver.S.P.L.)','ぺんたきゅーぶじーてぃーあーるえっくすばーじょんえすぴーえる'], //
    ['Perfect Plan','ぱーふぇくとぷらん'],
    ['Persephone','ぺるせぽね'],
    ['Pharaoh','ふぁらお'],
    ['Piano Samurai','ぴあのさむらい'],
    ['Pink Rose','ぴんくろーず','ハート'],
    ['Pink Rose(譜面変更前)','ぴんくろーずふめんへんこうまえ','ハート'],
    ['Pinky Happy Crazy','ぴんきーはっぴーくれいじー'],
    ['Play back hate you','ぷれいばっくへいとゆー'],
    ['Playball','ぷれいぼーる'],
    ['Playing With Fire','ぷれいんぐうぃずふぁいあ'],
    ['Plazma','ぷらずま'],
    ['Plea Per Phase','ぷりーぱーふぇいず'], //
    ['Pollinosis','ぽりのしす'],
    ['Poppin\' Soda','ぽっぴんそーだ'],
    ['PopなEDEN','ぽっぷなえでん'],
    ['Pout','ぱうと'],
    ['Power of Love','ぱわーおぶらヴ'],
    ['Prelude','ぷれりゅーど'],
    ['Presto','ぷれすと'],
    ['Pretty Punisher','ぷりてぃーぱにっしゃー'],
    ['Prince on a star','ぷりんすおんあすたー'],
    ['Programmed Genom','仕組遺伝','ぷろぐらむどげのむ'],
    ['Programmed Life','仕組生命','仕組人生','ぷろぐらむどらいふ'],
    ['Programmed Sun','仕組太陽','ぷろぐらむどさん'],
    ['Programmed Sun (xac Antarctic Ocean mix)','仕組海洋','ぷろぐらむどさんざっくあんたーくてぃっくおーしゃんみっくす'],
    ['Programmed Universe','仕組宇宙','ぷろぐらむどゆにヴぁーす'],
    ['Programmed World','仕組世界','ぷろぐらむどわーるど'],
    ['Prohibited Props','ぷろひびてっどぷろっぷす'],
    ['Psychedelic Intelligence','さいけでりっくいんてりじぇんす'],
    ['Psycho Sheep Riddim','さいこしーぷりでぃむ'],
    ['Punching Down (IIDX Mix)','ぱんちんぐだうんつーでぃーえっくすみっくす'],
    ['Queen Kaguya','くいーんかぐや'],
    ['Queen\'s Tragedy','くいーんずとらじでぃー'],
    ['Quick Silver','くぃっくしるヴぁー'],
    ['Quickening','くいっけにんぐ','くいっくにんぐ'],
    ['R2','あーるつー'],
    ['R5','あーるふぁいヴ'],
    ['RALLY \'25','らりーにじゅうご'],
    ['RAVE SYNDROME','れいヴしんどろーむ'],
    ['REMEMBER ME','りめんばーみー'],
    ['Remember You','りめんばーゆー'],
    ['REMINISCENCE','れみにせんす'],
    ['REPLAY','りぷれい'],
    ['RESISTANCE','れじすたんす'],
    ['RESONATE 1794','りぞねいといちななきゅうよん'],
    ['REcorrection','りこれくしょん'],
    ['RIDE ON THE LIGHT (HI GREAT MIX)','らいどおんざらいとはいぐれいとみっくす'],
    ['RISE','らいず'],
    ['RISING FIRE HAWK','らいじんぐふぁいあほーく'],
    ['RISLIM','りすりむ'],
    ['RISLIM -Remix-','りすりむりみっくす'],
    ['RIZING YOU UP','らいじんぐゆーあっぷ'],
    ['RIZING-GAMERS.','らいじんぐげーまーず'],
    ['ROCK ME NOW','ろっくみーなう'],
    ['ROK DA WORLD','ろっくだわーるど'],
    ['ROMEO&JULIET','ろみおあんどじゅりえっと'],
    ['ROTTERDAM SHOGUN','ろってるだむしょうぐん'],
    ['ROZA DE ANDALUCIA','ろさであんだるしあ'],
    ['RUGGED ASH','らぎっどあっしゅ','らげっどあっしゅ'],
    ['Radical Faith','らでぃかるふぇいす'],
    ['Rainbow after snow','れいんぼーあふたーすのー'],
    ['Rainstorm','れいんすとーむ'],
    ['Raise your hands','れいずゆあはんず'],
    ['Raspberry Potion(feat.あれたん♡ & ぎゃるのしん☆)','らずべりーぽーしょんふぃーちゃりんぐあれたんぎゃるのしん'],
    ['Rave lithosphere','れいヴりそすふぃあ'],
    ['Re:GENERATION','りじぇねれーしょん'],
    ['Re:Story','りすとーりー'],
    ['Ready To Rockit Blues','れでぃーとぅーろっくいっとぶるーす'],
    ['Ready To Rockit Blues(譜面変更前)','れでぃーとぅーろっくいっとぶるーすふめんへんこうまえ'],
    ['Real','りある'],
    ['Really Love','りありーらヴ'],
    ['Recollection','りこれくしょん'],
    ['Red Determination','れっどでたーみねいしょん'],
    ['Red Nikita','れっどにきーた'],
    ['Red Rocket Rising','れっどろけっとらいじんぐ'],
    ['Red Soul','れっどそうる'],
    ['Reflection Into the EDEN','りふれくしょんいんとじえでん'],
    ['Regina vespaE','れじーなヴぇすぱえ','れじーなうぇすぱえ'],
    ['Regulus','れぐるす'],
    ['Rejection Girl','りじぇくしょんがーる'],
    ['Release The Music','りりーすざみゅーじっく'],
    ['Rewind Time','りわいんどたいむ'],
    ['Ride To The Core','らいどとぅーざこあ'],
    ['Riff//rain','りふれいん'],
    ['Rise Circuit','らいずさーきっと'],
    ['Rise\'n Beauty','らいずんびゅーてぃ'],
    ['Rise\'n Beauty(CSDJT)','らいずんびゅーてぃしーえすでぃーじぇいとぅるーぱーず'],
    ['Rising in the Sun(original mix)','らいじんぐいんざさんおりじなるみっくす'],
    ['Rising in the Sun(original mix)(譜面変更前)','らいじんぐいんざさんおりじなるみっくすふめんへんこうまえ'],
    ['Ritual of Anubis','りちゅあるおぶあぬびす'],
    ['Rock Da House','ろっくだはうす'],
    ['Rock It','ろっくいっと'],
    ['Romanticが止まらない','ろまんてぃっくがとまらない'],
    ['Roots of my way!','るーつおぶまいうぇい'],
    ['Rosa azuL','ろさあじゅーる','ろさあずーる'],
    ['Roulette','るーれっと'],
    ['Round and Round','らうんどあんどらうんど'],
    ['Routing','るーてぃんぐ'],
    ['Rowdy','らうでぃ'],
    ['Rub-a Dub-a','らばだば'],
    ['Rubrum Piano','らぶらむぴあの'],
    ['Ruler or Loser','るーらーおあるーざー'],
    ['S!ck','しっく'],
    ['S!ck (Nhato Remix)','しっくなはとりみっくす'],
    ['S-Bahn','えすばーん'],
    ['SA.YO.NA.RA. SUPER STAR','さよならすーぱーすたー'],
    ['SABER WING','せいばーうぃんぐ'],
    ['SAMBA DE JANEIRO','さんばでじゃねいろ'],
    ['SAMSARA','さんさーら'],
    ['SAMURAI-Scramble','さむらいすくらんぶる'],
    ['SCHWARZSCHILD FIELD','しゅばるつしるとふぃーるど'],
    ['SCORE','すこあ'],
    ['SCORE(譜面変更前)','すこあふめんへんこうまえ'],
    ['SEQUENCE CAT','シケ猫','しーけんすきゃっと','しーくぇんすきゃっと'],
    ['SEXYSEXYCHEVY','せくしーせくしーちぇヴぃ'],
    ['SHADE','しぇいど'],
    ['SHELTER OF THE MIND','しぇるたーおぶざまいんど'],
    ['SHIFT','しふと'],
    ['SHINING☆DANCE','しゃいにんぐだんす'],
    ['SHOOTING STAR','しゅーてぃんぐすたー'],
    ['SHOX','しょっくす'],
    ['SIGMA','しぐま'],
    ['SILKY BRAVE','しるきーぶれいヴ'],
    ['SINOBUZ Fantasy','しのばずふぁんたじー'],
    ['SNOW','すのー'],
    ['SNOW(譜面変更前)','すのーふめんへんこうまえ'],
    ['SOLID GOLD','そりっどごーるど'],
    ['SOLITON BEAM','そりとんびーむ'],
    ['SOLITON BEAM(譜面変更前)','そりとんびーむふめんへんこうまえ'],
    ['SOMETHING WONDERFUL','さむしんぐわんだふる'],
    ['SOUND OF GIALLARHORN','さうんどおぶぎゃらるほるん'],
    ['SPACE FIGHT','すぺーすふぁいと'],
    ['SPARK !','すぱーく'],
    ['SPARK ! -essential RMX-','すぱーくえっせんしゃるりみっくす'],
    ['SPARK IN THE NIGHT','すぱーくいんざないと'],
    ['SPEED','すぴーど'],
    ['SPEED ROCKER','すぴーどろっかー'],
    ['SPEEDY CAT','すぴーでぃーきゃっと'],
    ['SPLASH!!!!!!!!!','すぷらっしゅ'],
    ['SPRING RAIN (LLUVIA DE PRIMAVERA)','すぷりんぐれいんじゅヴぃあでぷりまヴぇーら'],
    ['STAR BEAT','すたーびーと'],
    ['STAR DREAM','すたーどりーむ'],
    ['STAR FIELD','すたーふぃーるど'],
    ['STARLIGHT JUNCTION','すたーらいとじゃんくしょん'],
    ['STARLiGHT','すたーらいと'],
    ['STELLAR WIND','すてらーうぃんど','すてらうぃんど'],
    ['STILL IN MY HEART','すてぃるいんまいはーと'],
    ['STOIC HYPOTHESIS','すといくはいぽせしす'],
    ['STRAIGHT TO THE STARS','すとれいととぅーざすたーず'],
    ['SUNLiGHT (IIDX Mix)','さんらいとつーでぃーえっくすみっくす'],
    ['SUPER HEROINE!!','すーぱーひろいん'],
    ['SURVIVOR','さヴぁいヴぁー'],
    ['SWEET LAB','すうぃーとらぼ','すうぃーとらぶ'],
    ['SWEET LAB(譜面変更前)','すうぃーとらぼふめんへんこうまえ','すうぃーとらぶふめんへんこうまえ'],
    ['SWEETEST SAVAGE','すうぃーてすとさヴぇーじ'],
    ['SWEETEST SAVAGE(譜面変更前)','すうぃーてすとさヴぇーじふめんへんこうまえ'],
    ['SWITCH','すうぃっち'],
    ['SWITCH(CSDJT)','すうぃっちしーえすでぃーじぇいとぅるーぱーず'],
    ['Sakura Mirage','さくらみらーじゅ'],
    ['Sakura Reflection','さくらりふれくしょん'],
    ['Sarutobi Champion is 拙者','さるとびちゃんぴおんいずせっしゃ'],
    ['Scandal','すきゃんだる'],
    ['Scarlet Moon','すかーれっとむーん'],
    ['Scharfrichter','しゃーふりひたー','しゃるふりひたー','色欲'],
    ['Seaside Labyrinth','しーさいどらびりんす'],
    ['Secret Rouge','しーくれっとるーじゅ'],
    ['Secret Tale','しーくれっとている'],
    ['Secret of Love','しーくれっとおぶらヴ'],
    ['See You Again','しーゆーあげいん'],
    ['Seize the Day','しーずざでい'],
    ['Selfish Sweet','せるふぃっしゅすうぃーと'],
    ['Sellout','せるあうと'],
    ['Serious?','しりあす'],
    ['Session 1 -Genesis-','せっしょんわんじぇねしす'],
    ['Several Words','せヴぇらるわーず'],
    ['Shades of Grey','しぇいずおぶぐれい'],
    ['Shadow World','しゃどーわーるど'],
    ['Shakin\' 31','しぇいきんさーてぃーわん'],
    ['Shamshir','しゃむしーる'],
    ['Shapeshifter','しぇいぷしふたー'],
    ['Shattered control','しゃたーどこんとろーる'],
    ['She is my wife','しーいずまいわいふ'],
    ['Shining World','しゃいにんぐわーるど'],
    ['Shirdal','しるだる'],
    ['Shiva','しヴぁ'],
    ['Shoot\'Em All','しゅーてむおーる'],
    ['Shooting Star','しゅーてぃんぐすたー'],
    ['Show Me All Your Love','しょうみーおーるゆあらヴ'],
    ['Show Time','しょーたいむ','しょうたいむ'],
    ['Sidechained Threats','さいどちぇいんどすれっつ'],
    ['Signs and Wonders','さいんずあんどわんだーず'],
    ['Silly Love','しりーらヴ'],
    ['Silvia Drive','しるヴぃあどらいヴ'],
    ['Six String Proof','しっくすすとりんぐぷるーふ'],
    ['Ska-sh All Neurons!!','すかっしゅおーるにゅーろんず'],
    ['Skratch Education Lv-1','すくらっちえでゅけーしょんれヴぇるわん'],
    ['Skyscraper','すかいすくれいぱー'],
    ['Skywalking','すかいうぉーきんぐ'],
    ['Sleepless days','すりーぷれすでいず'],
    ['Slumber☆Party','すらんばーぱーてぃ'],
    ['Smell Like This','すめるらいくでぃす'],
    ['Smoke','すもーく'],
    ['Smug Face -どうだ、オレの生き様は- (ONLY ONE EDITION)','すまっぐふぇいすどうだおれのいきざまはおんりーわんえでぃしょん'],
    ['SnapSkipSpark','すなっぷすきっぷすぱーく'],
    ['Snow Goose','すのぐ','すのーぐーす'],
    ['So Fabulous !!','そーふぁびゅらす'],
    ['So Punky','そーぱんきー'],
    ['So Real','そーりある'],
    ['So What','そーわっと'],
    ['Somebody Like You','さむばでぃーらいくゆー'],
    ['Somebody Like You(譜面変更前)','さむばでぃーらいくゆーふめんへんこうまえ'],
    ['Son, not gabba now','そんながばな'],
    ['Space In Time','すぺーすいんたいむ'],
    ['Space Time','すぺーすたいむ'],
    ['Sparkle Smilin\'','すぱーくるすまいりん'],
    ['Special One','すぺしゃるわん'],
    ['Speculation','すぺきゅれいしょん'],
    ['Sphere','すふぃあ'],
    ['Spin the disc','すぴんざでぃすく'],
    ['Spinning Around','すぴにんぐあらうんど'],
    ['Spooky','すぷーきー'],
    ['Star Trail','すたーとれいる'],
    ['Starry Night','すたりーないと'],
    ['State Of The Art','すていとおぶじあーと'],
    ['State Of The Art(譜面変更前)','すていとおぶじあーとふめんへんこうまえ'],
    ['Static State','すたてぃっくすてーと'],
    ['Stay my side','すていまいさいど'],
    ['Stepper','すてっぱー'],
    ['Stleq','すとれく'],
    ['Stylus','すたいらす'],
    ['Submerge Serenade','さぶまーじせれなーで'],
    ['Substance','さぶすたんす'],
    ['Sugar Drippin\'','しゅがーどりっぴん'],
    ['Sugarplum','しゅがーぷらむ'],
    ['Summer','さまー'],
    ['Summer Vacation(CU mix)','さまーヴぁけーしょんしーゆーみっくす'],
    ['Summerblue','さまーぶるー'],
    ['Sun Field','さんふぃーるど'],
    ['Sunny Day Vibes','さにーでいヴぁいぶす'],
    ['Sunrise','さんらいず'],
    ['Sunshine Hero','さんしゃいんひーろー'],
    ['Super Duper Racers','すーぱーどゅーぱーれーさーず'],
    ['Surf on the Light','さーふおんざらいと'],
    ['Sweet Radar','すうぃーとれーだー','すうぃーとれいだー'],
    ['Swing My Wonderland','すうぃんぐまいわんだーらんど'],
    ['T.R.O.L.L.','とろる','とろーる'],
    ['TA・DA ☆ YO・SHI','ただよし'],
    ['TECHNO RUMBLE','てくのらんぶる'],
    ['TEXTURE','てくすちゃー'],
    ['THE ANCIENT KING IS BACK','じえんしぇんときんぐいずばっく'],
    ['THE BLACK KNIGHT','ざぶらっくないと'],
    ['THE CUBE','ざきゅーぶ'],
    ['THE DETONATOR','ざでとねいたー'],
    ['THE DOOR INTO RAINBOW','ざどあいんとぅれいんぼー'],
    ['THE EARTH LIGHT','じあーすらいと'],
    ['THE FALLEN','ざふぉーるん'],
    ['THE LAST STRIKER','ざらすとすとらいかー'],
    ['THE SAFARI','ざさふぁり'],
    ['THE SHINING POLARIS','ざしゃいにんぐぽらりす'],
    ['THE SHINING POLARIS(kors k mix)','ざしゃいにんぐぽらりすこーすけみっくす'],
    ['THE SHINING POLARIS(kors k mix)(譜面変更前)','ざしゃいにんぐぽらりすこーすけみっくすふめんへんこうまえ'],
    ['THE TIME MACHINE','ざたいむましーん'],
    ['TITANIUM RIDERS','ちたにうむらいだーず'],
    ['TOE JAM','とーじゃむ'],
    ['TOKAKU=ALMiRAJ','とかくあるみらーじゅ'],
    ['TOMORROW','とぅもろー'],
    ['TRIP MACHINE PhoeniX','とりっぷましんふぇにっくす'],
    ['TRIP MACHINE PhoeniX(譜面変更前)','とりっぷましんふぇにっくすふめんへんこうまえ'],
    ['TRIP THE DEEP','とりっぷざでぃーぷ'],
    ['TYPE MARS(G-Style Mix)','たいぷまーずじーすたいるみっくす'],
    ['Tail Lights','ているらいつ'],
    ['Take It Easy','ていくいっといーじー'],
    ['Take Me Higher','ていくみーはいあー'],
    ['Take My Life','ていくまいらいふ'],
    ['Technicolour Dreams','てくにからーどりーむず'],
    ['Tell Me More…','てるみーもあ','R&B'],
    ['Temple of Anubis','てんぷるおぶあぬびす'],
    ['That Feeling','ざっとふぃーりんぐ'],
    ['The Beauty Of Silence','ざびゅーてぃーおぶさいれんす'],
    ['The Best of Both Worlds','ざべすとおぶぼーすわーるず'],
    ['The Biggest Roaster','ざびっげすとろーすたー'],
    ['The Commanders','ざこまんだーず'],
    ['The Dirty of Loudness','ざだーてぃーおぶらうどねす'],
    ['The Hope of Tomorrow','ざほーぷおぶとぅもろー'],
    ['The Hope of Tomorrow(CSDD)','ざほーぷおぶとぅもろーしーえすでぃすとーてっど'],
    ['The Revolution (VIP Mix)','ざれヴぉりゅーしょんヴぃーあいぴーみっくす'],
    ['The Story Begins','ざすとーりーびぎんず'],
    ['The Wind of China Express(The 4th Mashup)','ざうぃんどおぶちゃいなえくすぷれすざふぉーすまっしゅあっぷ'],
    ['The end of my spiritually','じえんどおぶまいすぴりちゅありー'],
    ['The setting sun(burst)','ざせってぃんぐさんばーすと'],
    ['Theory','せおりー'],
    ['Think of me','しんくおぶみー'],
    ['This is Love','でぃすいずらヴ'],
    ['Time Distortion pt.2(IIDX Edit)','たいむでぃすとーしょんぱーとつーつーでぃーえっくすえでぃっと'],
    ['Time To Empress','たいむとぅーえんぷれす'],
    ['To The Paradise','とぅーざぱらだいす'],
    ['To my star','とぅーまいすたー'],
    ['To the Future','とぅーざふゅーちゃー'],
    ['Tomorrow Perfume','とぅもろーぱふゅーむ'],
    ['Tonight?','とぅないと'],
    ['Too Late Snow','とぅーれいとすのー'],
    ['Tori-no-kimochi','とりのきもち'],
    ['ToyCube Pf.(RX-Ver.S.P.L.)','といきゅーぶぴーえふあーるえっくすばーじょんえすぴーえる'], //
    ['Tp-RZ','とぱーず','てぃーぴーあーるぜっと'],
    ['Transport','とらんすぽーと'],
    ['Treasure×Star','とれじゃーすたー'],
    ['Tropical April','とろぴかるえいぷりる'],
    ['Troposphere','とろぽすふぃあ'],
    ['Trust -MATERIAL ver- (IIDX Edition)','とらすとまてりあるばーじょんつーでぃーえっくすえでぃしょん'],
    ['Twilight Warp','とわいらいとわーぷ'],
    ['Two DAYS OF LOVE','つーでいずおぶらヴ'],
    ['U.S.A.','ゆーえすえー'],
    ['UMMU','うっむ','ゆーめいくみーあっぱー','ゆーえむえむゆー'],
    ['UNDERWORLD HOLOGRAPHY','あんだーわーるどほろぐらふぃー'],
    ['UNDO THE NIGHT','あんどぅーざないと'],
    ['UNITE THE HEART','ゆないとざはーと'],
    ['Ubiquitous Fantastic Ride','ゆびきたすふぁんたすてぃっくらいど'],
    ['Uh-Oh','あっおー','おっおー'],
    ['Under Construction','あんだーこんすとらくしょん'],
    ['Under the Sky','あんだーざすかい'],
    ['Unicorn tail','ゆにこーんている'],
    ['Urban Constellations','あーばんこんすてれいしょんず'],
    ['Usual Days-remix','ゆーじゅあるでいずりみっくす'],
    ['V2','ぶいつー'],
    ['V35','ぶいさんじゅうご'],
    ['VALLIS-NERIA','ヴぁりすねりあ'],
    ['VANISHING POINT','ヴぁにしんぐぽいんと'],
    ['VEGA','べが'],
    ['VIVID DEBUT!','ヴぃヴぃっどでびゅー'],
    ['VJ ARMY','ぶいじぇーあーみー'],
    ['VJ ARMY(譜面変更前)','ぶいじぇーあーみーふめんへんこうまえ'],
    ['VOX UP(譜面変更前)','ヴぉっくすあっぷふめんへんこうまえ'],
    ['VR - Virtual Reality (prod.by Snail\'s House)','ぶいあーるヴぁーちゃるりありてぃぷろでゅーすどばいすねいるずはうす'],
    ['Valgus','ヴぁるがす'],
    ['Vector','ヴぇくたー'],
    ['Ventriloquist','ヴぇんとりろくぃすと'],
    ['Vibing! Shake it!','ヴぁいびんぐしぇいくいっと'],
    ['Victory Of Ravers','ヴぃくとりーおぶれいヴぁーず'],
    ['Vienna','ヴぃえな'],
    ['Violet Rose','ヴぁいおれっとろーず'],
    ['Virus Funk','ヴぁいらすふぁんく'],
    ['Vitamin','びたみん','ヴぁいたみん'],
    ['Voo Doo Bamboleo','ヴーどぅーばんぼれお'],
    ['Votania Beat','ヴぉたにあびーと'],
    ['Votum stellarum -Hommarju Remix-','ヴぉーとぅむすてらるむほまるじゅりみっくす'],
    ['Voxane','ヴぉくさーぬ'],
    ['Vulkan','ヴぁるかん'],
    ['WAKE UP NOW','うぇいくあっぷなう'],
    ['WANNA TELL THAT WORD','わなてるざっとわーど'],
    ['WAR GAME','うぉーげーむ'],
    ['WE LOVE SHONAN','うぃーらヴしょうなん'],
    ['WHAT\'S NEXT?','わっつねくすと'],
    ['WILD FIRE','わいるどふぁいあ'],
    ['WISE UP!','わいずあっぷ'],
    ['WISH(EUROBEAT MIX)','うぃっしゅゆーろびーとみっくす'],
    ['WOBBLE IMPACT','わぶるいんぱくと'],
    ['Wanna Party?','わなぱーてぃ'],
    ['Warrior','うぉーりあー'],
    ['Watch out!!','うぉっちあうと','わっちあうと'],
    ['WaterCube Pf.(RX-Ver.S.P.L.)','うぉーたーきゅーぶぴーえふあーるえっくすばーじょんえすぴーえる'], //
    ['Watermelon Explosion','うぉーたーめろんえくすぷろーじょん'],
    ['We are Disっ娘よっつ打ち命','うぃーあーでぃすっこよっつうちいのち'],
    ['We\'re so Happy (P*Light Remix) IIDX ver.','うぃーあーそーはっぴーぴーらいとりみっくすつーでぃーえっくすばーじょん'],
    ['Welcome to the Mosh Pit','うぇるかむとぅーざもっしゅぴっと'],
    ['Wheel of Journey','ほいーるおぶじゃーにー'],
    ['When I Met U','うぇんあいめっとゆー'],
    ['Why did you go away','わいでぃでゅーごーあうぇい'],
    ['Wing of Hearts','うぃんぐおぶはーつ'],
    ['Winning Eleven9 Theme(IIDX EDITION)','うぃにんぐいれヴんないんてーまつーでぃーえっくすえでぃしょん'],
    ['With You','うぃずゆー'],
    ['With your Smile','うぃずゆあすまいる'],
    ['Won(*3*)Chu KissMe!','うぉんちゅきすみー'],
    ['Wonder Bullfighter','わんぶる','わんだーぶるふぁいたー'],
    ['Wonderful Escape','わんだふるえすけいぷ'],
    ['Wonderland','わんだーらんど'],
    ['World Wide Love','わーるどわいどらヴ'],
    ['X-rated','えっくすれいてっど'],
    ['X-ray binary','えっくすれいばいなりー'],
    ['XANADU OF TWO','ざなどぅーおぶつー'],
    ['XENON II ～TOMOYUKIの野望～','ぜのんつーとものゆきのやぼう'],
    ['XINOBIKILL','しのびきる'],
    ['Xepher','ぜふぁー'],
    ['Xyndrome','しんどろーむ'],
    ['Y&Co. is dead or alive(譜面変更前)','わいあんどこーいずでっどおああらいヴふめんへんこうまえ'],
    ['Y31','わいさんじゅういち'],
    ['YELLOW FROG from Steel Chronicle','いえろーふろっぐふろむすてぃーるくろにくる'],
    ['Yabis Starlight','やびすすたーらいと'],
    ['Yellow Sketch(RX-Ver.S.P.L.)','いえろーすけっちあーるえっくすばーじょんえすぴーえる'], //
    ['Yellow Sunrise','いえろーさんらいず'],
    ['You Really Got Me','ゆーりありーごっとみー'],
    ['You Were The One','ゆーわーざわん'],
    ['You\'ll say "Now!"','許せない','ゆーるせいなう'],
    ['Your Body','ゆあぼでぃ'],
    ['Yum Yum Jelly','やむやむじぇりー'],
    ['ZED','ぜっど'],
    ['ZENDEGI DANCE','ぜんでぎだんす'],
    ['ZERO-ONE','ぜろわん'],
    ['ZEROIN ON THE LIGHT','ぜろいんおんざらいと'],
    ['Zenius -I- vanisher','じーにあすわんヴぁにっしゃー','じいにあすいちヴぁにっしゃー'],
    ['ＵＬＴｉＭΛＴＥ','あるてぃめいと','あるてぃめっと'], //
    ['abstract','あぶすとらくと'],
    ['airflow -dreaming of the sky- Game Edition','えあーふろーどりーみんぐおぶざすかいげーむえでぃしょん'],
    ['alla turca con passione','あらとぅるかこんぱっしょーね'],
    ['apo:llioth','あぽりおす'],
    ['avant-guerre','あヴぁんげーる'],
    ['awakening','あうぇいくにんぐ'],
    ['ay carumba!!!!','あいからんば'],
    ['bag','ばぐ'],
    ['bass 2 bass','べーすとぅーべーす'],
    ['beatAffection','びーとあふぇくしょん'],
    ['beatonic nation','びーとにっくねいしょん'],
    ['being torn the sky','びーいんぐとーんざすかい'],
    ['believe...?','びりーヴ'],
    ['bit mania','びっとまにあ'],
    ['bloomin\' feeling','ぶるーみんふぃーりんぐ'],
    ['bluemoon','ぶるーむーん'],
    ['breathless','ぶれすれす'],
    ['chaos eater -IIDX edition-','かおすいーたーつーでぃーえっくすえでぃしょん'],
    ['chaplet -IIDX re:build-','ちゃぷれっとつーでぃーえっくすりびるど'],
    ['connective','こねくてぃヴ'],
    ['crew','くるー'],
    ['diagram','だいあぐらむ'],
    ['dissolve','でぃぞるヴ'],
    ['dong-tepo no.1','どんてぽなんばーわん'],
    ['double thrash','だぶるすらっしゅ'],
    ['dual control','でゅあるこんとろーる'],
    ['earth scape','あーすすけいぷ'],
    ['earth-like planet','あーすらいくぷらねっと'],
    ['empathy','えんぱしー'],
    ['end of world','えんどおぶわーるど'],
    ['entrance','えんとらんす'],
    ['era (nostalmix)','えらのすたるみっくす'],
    ['era (step mix)','えらすてっぷみっくす'],
    ['esrev:eR','りばーす','すーばり'],
    ['evergreen','えヴぁーぐりーん'],
    ['everlastingeuphoria:','えヴぁーらすてぃんぐゆーふぉりあ'],
    ['examination leave','いぐざみねーしょんりーヴ'],
    ['fairy cocktail','ふぇありーかくてる'],
    ['feeling of love','ふぃーりんぐおぶらヴ'],
    ['fixer','ふぃくさー'],
    ['fly through the night','ふらいするーざないと'],
    ['foreplay','ふぉあぷれい'],
    ['four-leaf','ふぉーりーふ'],
    ['fun','ふぁん'],
    ['garden','がーでん'],
    ['gentle stress','じぇんとるすとれす'],
    ['gentle stress(譜面変更前)','じぇんとるすとれすふめんへんこうまえ'],
    ['get set mind','げっとせっとまいんど'],
    ['heaven above','へヴんあばーヴ','へヴんあぼーヴ'],
    ['i feel ...','あいふぃーる'],
    ['i-ii','あいつー'],
    ['iFUTURELIST','あいふゅーちゃりすと'],
    ['illuminate','いるみねいと'],
    ['in motion','いんもーしょん'],
    ['in my eyes','いんまいあいず'],
    ['in the Sky','いんざすかい'],
    ['insist','いんしすと'],
    ['into the battlefield','いんとぅーざばとるふぃーるど'],
    ['jelly kiss','じぇりーきす'],
    ['jelly kiss-Midihead\'s Smack Mix-','じぇりーきすみでぃへっどずすまっくみっくす'],
    ['jewelry girl*','じゅえりーがーる','ジュエリーロック'],
    ['lights','らいつ'],
    ['lights(譜面変更前)','らいつふめんへんこうまえ'],
    ['listen to yourself','りっすんとぅーゆあせるふ'],
    ['lowercase lifetime','ろわーけーすらいふたいむ'],
    ['m1dy Deluxe','みでぃでらっくす'],
    ['m1dy Dynamic','みでぃだいなみっく'],
    ['m1dy Festival','みでぃふぇすてぃヴぁる'],
    ['madrugada','まどるがーだ'],
    ['madrugada(譜面変更前)','まどるがーだふめんへんこうまえ'],
    ['mind the gap','まいんどざぎゃっぷ'],
    ['minimalian','みにまりあん'],
    ['mnemoniq','にーもにっく'],
    ['n\'pa pa BBQ','んぱばーびーびーきゅー'],
    ['naughty girl@Queen\'s Palace','のーてぃがーるくいーんずぱれす'],
    ['neogenesis','ねおじぇねしす'],
    ['never…','ねヴぁー'],
    ['nostos','のすとす'],
    ['of the first magnitude','おぶざふぁーすとまぐにちゅーど'],
    ['out of disk space','あうとおぶでぃすくすぺーす'],
    ['outer wall','あうたーうぉーる'],
    ['pandora','ぱんどら'],
    ['paramnesia','ぱらむねしあ'],
    ['passionate fate','ぱっしょねいとふぇいと'],
    ['pique','ぴけ'],
    ['planarian','ぷらなりあん'],
    ['portal','ぽーたる'],
    ['prompt','ぷろんぷと'],
    ['radius','れいでぃうす','れいでぃあす'],
    ['rainbow flyer','れいんぼーふらいやー'],
    ['rainbow guitar weeps','れいんぼーぎたーうぃーぷす'],
    ['rainbow rainbow','れいんぼーれいんぼー'],
    ['refractive index','りふらくてぃヴいんでっくす'],
    ['rottel-da-sun','ろってるださん','ロッテルダムテクノ'],
    ['rottel-the-Mercury','ろってるざまーきゅりー'],
    ['rough percussionythm','らふぱーかっしょにずむ'],
    ['satfinal','さっとふぁいなる'],
    ['scar in the earth','すかーいんざあーす'],
    ['scherzo','すけるつぉ'],
    ['shuriken','しゅりけん'],
    ['sink into the dream','しんくいんとぅーざどりーむ'],
    ['smile','すまいる'],
    ['soldier\'s waltz','そるじゃーずわるつ'],
    ['soldier\'s waltz(譜面変更前)','そるじゃーずわるつふめんへんこうまえ'],
    ['sometime','さむたいむ'],
    ['spiral galaxy -L.E.D. STYLE SPREADING PARTICLE BEAM MIX-','すぱいらるぎゃらくしーえるいーでぃーすたいるすぷれでぃんぐぱーてぃくるびーむみっくす'],
    ['squall','すこーる'],
    ['starmine','すたーまいん'],
    ['stoic','すといっく'],
    ['subtractive','さぶとらくてぃヴ'],
    ['super highway','すーぱーはいうぇい'],
    ['switch','すいっち'],
    ['symbolic','しんぼりっく'],
    ['symptom','しんぷとむ'],
    ['sync','しんく'],
    ['tablets','たぶれっつ'],
    ['take me higher','ていくみーはいあー'],
    ['tant pis pour toi','とんぴぷーとわ'],
    ['the shadow','ざしゃどー'],
    ['the trigger of innocence','ざとりがーおぶいのせんす'],
    ['thunder','さんだー'],
    ['tiger yamato','たいがーやまと'],
    ['toxic','ときしっく'],
    ['toy boxer','といぼくさー'],
    ['traces','とれーしーず'],
    ['u gotta groove -extend joy style-','ゆーごったーぐるーヴえくすてんどじょいすたいる'],
    ['vault of heaven','ヴぉーるとおぶへヴん'],
    ['voice of echo.','ヴぉいすおぶえこー'],
    ['wish','うぃっしゅ'],
    ['with me...','うぃずみー'],
    ['with you…','うぃずゆー'],
    ['xenon','ぜのん'],
    ['yamabiko (SINOBUZ Edition)','やまびこしのばずえでぃしょん'],
    ['¡Viva!','びヴぁ'],
    ['あいつら全員同窓会','あいつらぜんいんどうそうかい'],
    ['うさ☆かめ 大戦争！','うさかめだいせんそう'],
    ['お命ちょうDAI！901娘','おいのちちょうだいくのいちむすめ'],
    ['お願いアインシュタイン','おねがいあいんしゅたいん'],
    ['かげぬい ～ Ver.BENIBOTAN ～','かげぬいばーじょんべにぼたん'],
    ['か・し・ま・し☆PUMP UP！','かしましぱんぷあっぷ'],
    ['こっちを向いてよ','こっちをむいてよ'],
    ['それが、ボクの使命～レスキュー隊長 メンキュー～','それがぼくのしめいれすきゅーたいちょうめんきゅー'],
    ['ちゅ、多様性。','ちゅたようせい'],
    ['とろぴかる倶楽部','とろぴかるくらぶ'],
    ['ぷろぐれっしぶ時空少女！うらしまたろ子ちゃん！','ぷろぐれっしぶじくうしょうじょうらしまたろこちゃん'],
    ['めうめうぺったんたん！！ (ZAQUVA Remix)','めうめうぺったんたんざくヴぁりみっくす'],
    ['アタシ完全絶対正義ちゃん！','あたしかんぜんぜったいせいぎちゃん'],
    ['アタック NO.3','あたっくなんばーすりー'],
    ['エコ爺','えこじじい'],
    ['エディブルフラワーの独白','えでぃぶるふらわーのどくはく'],
    ['オルタネイトβ','おるたねいとべーた'],
    ['オレはビートマニア！お前は何マニア？','おれはびーとまにあおまえはなにまにあ'],
    ['オールトの雲','おーるとのくも'],
    ['キャッシュレスは愛情消すティッシュ','きゃっしゅれすはあいじょうけすてぃっしゅ'],
    ['クルクル☆ラブ～Opioid Peptide MIX～','くるくるらぶおぴおいどぺぷちどみっくす'],
    ['グラナダの風','ぐらなだのかぜ'],
    ['サヨナラ・ヘヴン-Celtic Chip Dance Mix-','さよならへヴんけるてぃっくちっぷだんすみっくす'],
    ['パラドキシカル・タイムリープトライアル(Short Ver.)','ぱらどきしかるたいむりーぷとらいあるしょーとばーじょん'],
    ['ビビッド ☆+*。キラキライム','びびっどきらきらいむ'],
    ['フェティッシュペイパー ～ 脇の汗回転ガール ～','ふぇてぃっしゅぺいぱーわきのあせかいてんがーる'],
    ['ベンガル vs. アムール Battle','べんがるヴぁーさすあむーるばとる'],
    ['マチ子の唄','まちこのうた'],
    ['マツケンサンバII','まつけんさんばつー'],
    ['ミストレス・アンに花束を','みすとれすあんにはなたばを'],
    ['ミッドナイト☆WAR','みっどないとうぉー'],
    ['ミッドナイト堕天使','みっどないとだてんし'],
    ['ミッドナイト堕天使(譜面変更前)','みっどないとだてんしふめんへんこうまえ'],
    ['ライオン好き','らいおんすき'],
    ['ロミとロボの宇宙飛行','ろみとろぼのうちゅうひこう'],
    ['ヒマワリ(譜面変更前)','ひまわりふめんへんこうまえ'],
    ['一途な恋 (HYPER J-EURO MIX)','いちずなこいはいぱーじぇいゆーろみっくす'],
    ['下弦の月','かげんのつき'],
    ['不死身ごっこ','ふじみごっこ'],
    ['世界の果てに約束の凱歌を -ReUnion-','せかいのはてにやくそくのがいかをりゆにおん'],
    ['今宵、ロマンス横丁。','こよいろまんすよこちょう'],
    ['令和(1991RAVE REMIX)','れいわいちきゅうきゅういちれいヴりみっくす'],//
    ['仮想空間の旅人たち','かそうくうかんのたびびとたち'],
    ['俺ら東京さ行ぐだ','おらとうきょうさいぐだ'],
    ['傷つけど、愛してる。','きずつけどあいしてる'],
    ['全力 SPECIAL VACATION!! ～限りある休日～','ぜんりょくすぺしゃるヴぁけーしょんかぎりあるきゅうじつ'],
    ['共犯ヘヴンズコード','きょうはんへヴんずこーど'],
    ['勇者','ゆうしゃ'],
    ['十六夜セツナ','いざよいせつな'],
    ['即席！脳直★ミュージックシステム','そくせきのうちょくみゅーじっくしすてむ'],
    ['取り残された美術(Arranged:HiZuMi)','とりのこされたびじゅつあれんじどひずみ'],
    ['可愛くてごめん','かわいくてごめん'],
    ['叶うまでは','かなうまでは'],
    ['合体せよ！ストロングイェーガー！！ (Ryu☆ remix)','がったいせよすとろんぐいぇーがーりゅーりみっくす'],
    ['君のハートにロックオン','きみのはーとにろっくおん'],
    ['唱','しょう'],
    ['夏色DIARY - L.E.D.-G STYLE MIX -','なついろだいありーえるいーでぃーじーすたいるみっくす'],
    ['夏風邪デスコ','なつかぜですこ'],
    ['夕焼け ～Fading Day～','ゆうやけふぇーでぃんぐでい'],
    ['夜のサングラス','よるのさんぐらす'],
    ['太陽SUNSUNボンジュールアバンチュール','たいようさんさんぼんじゅーるあばんちゅーる'],
    ['太陽～T・A・I・Y・O～','たいよう'],
    ['寝起きヤシの木','ねおきやしのき'],
    ['山岡晃の「クイズ！家事都合！」','やまおかあきらのくいずかじつごう'],
    ['怪物','かいぶつ'],
    ['恋は白帯、サンシロー','こいはしろおびさんしろー'],
    ['恋愛レボリューション21-秋葉工房mix-','れんあいれぼりゅーしょんにじゅういちあきばこうぼうみっくす'],
    ['惑','惑-perplexity-','まどい'], //
    ['惑星☆ロリポップ','わくせいろりぽっぷ'],
    ['愛包ダンスホール','あいぱいだんすほーる'],
    ['我ら完全無敵のアイドル!!','われらかんぜんむてきのあいどる'],
    ['抱きしめてモナムール','だきしめてもなむーる'],
    ['新時代','しんじだい'],
    ['旅人リラン','たびびとりらん'],
    ['星をこの手に','ほしをこのてに'],
    ['星屑ディスタンシア','ほしくずでぃすたんしあ'],
    ['昭和企業戦士荒山課長','しょうわきぎょうせんしあらやまかちょう'],
    ['最強頂戴girl♡','さいきょうちょうだいがーる'],
    ['月とミルク','つきとみるく'],
    ['月下繚乱','げっかりょうらん'],
    ['未来のプリズム','みらいのぷりずむ'],
    ['消極的セツナイズム','しょうきょくてきせつないずむ'],
    ['灼熱 Pt.2 Long Train Running','しゃくねつぱーとつーろんぐとれいんらんにんぐ'],
    ['灼熱Beach Side Bunny (Masayoshi Iimori Remix)','しゃくねつびーちさいどばにーまさよしいいもりりみっくす'],
    ['灼熱Beach Side Bunny (かめりあ\'s "Summertime D\'n\'B" Remix)','しゃくねつびーちさいどばにーかめりあずさまーたいむどらむんべーすりみっくす'],
    ['無意識のフィロソフィア','むいしきのふぃろそふぃあ'],
    ['爆ゼニ☆がってんワーカー','ばくぜにがってんわーかー'],
    ['犬に雨傘','いぬにあまがさ'],
    ['異心前進♪ぴょんぴょんぴょん','いしんぜんしんぴょんぴょんぴょん'],
    ['百恋ラブラスター','ひゃくれんらぶらすたー'],
    ['真夏の花・真夏の夢','まなつのはなまなつのゆめ'],
    ['真夜中のバベル','まよなかのばべる'],
    ['神様、つれない。','かみさまつれない'],
    ['突撃!ガラスのニーソ姫!','とつげきがらすのにーそひめ'],
    ['紅蓮華','ぐれんげ'],
    ['純真可憐デザイア','じゅんしんかれんでざいあ'],
    ['罠','わな'],
    ['華麗なる大犬円舞曲','かれいなるおおいぬえんぶきょく'],
    ['華麗なる！音戯探偵ひなビタ♫','かれいなるおとぎたんていひなびた'],
    ['蒼い衝動','あおいしょうどう'],
    ['表裏一体！？怪盗いいんちょの悩み♥','ひょうりいったいかいとういいんちょのなやみ'],
    ['見習い天使と星降りの丘','みならいてんしとほしふりのおか'],
    ['覚悟せよ！エンタンメ～ン ～より身の切り売り自暴自棄版～','かくごせよえんためーんよりみのきりうりじぼうじきばん'],
    ['超!!遠距離らぶ♡メ～ル','ちょうえんきょりらぶめーる'],
    ['踊','おど'],
    ['輪廻の鴉','りんねのからす'],
    ['追想快晴テーマパーク','ついそうかいせいてーまぱーく'],
    ['進捗ダメダメです','しんちょくだめだめです'],
    ['酔いどれ知らず','よいどれしらず'],
    ['金野火織の金色提言','こんのひおりのこんじきていげん'],
    ['錬成人間トリコロイダー','れんせいにんげんとりころいだー'],
    ['鏡像都市','きょうぞうとし'],
    ['閉塞的フレーション','へいそくてきふれーしょん'],
    ['開きたまえ！Next stAge！','ひらきたまえねくすとすてーじ'],
    ['雨のちパノラマセカイ','あめのちぱのらませかい'],
    ['電子になりたい','でんしになりたい'],
    ['霧幻メモリア','むげんめもりあ'],
    ['青の洞窟','あおのどうくつ'],
    ['風の谷のDREAM','かぜのたにのどりーむ'],
    ['飴玉','あめだま'],
    ['駅猫のワルツ','えきねこのわるつ'],
    ['魅惑のYUMMYスイーツ','みわくのやみーすいーつ'],
    ['魔法のかくれんぼ','まほうのかくれんぼ'],
    ['黎明の情','れいめいのじょう'],
    ['黒紅掬い','くろべにすくい'],

    // 難読
    ['閠槞彁の願い','ぎょくろうかのねがい'],
    ['鬼天','おにがみ'],
    ['伐折羅-vajra-','ばさら'],
    ['好吃来世deエレクトリック','はおちーらいせでえれくとりっく'],
    ['昏き甲鉄のヴェルガ','くらきこうてつのヴぇるが'],
    ['ALFARSHEAR 双神威に廻る夢','あるふぁるしあふたつかむいにまわるゆめ'],
    ['LETHEBOLG ～双神威に斬り咲けり～','れーてぼるぐふたつかむいにきりさけり'],
    ['九尾狐夜行','きゅうびこやぎょう'],
    ['津軽雪','つがるせつ'],
    ['焱影','ひかげ'],
    ['曼荼羅恋々','まんだられんれん'],
    ['忍恋花','しのびれんか'],
    ['夢縁','ゆめえにし'],
    ['獅子霞麗ノ舞','ししかすむうるわしのまい'],

    // 外語難読
    ['Claiomh Solais','くらうそらす'],
    ['Schlagwerk','しゅらーくヴぇるく'],
    ['Verflucht','ふぁーふるふと','ふぁふるーふと'],
    ['Turii ～Panta rhei～','とぅーりぱんたれい'],
    ['Geirskögul','げいるすこぐる'],
    ['DORNWALD ～Junge～','どるんばるとゆんげ'],
    ['Uaigh Gealaí','うぃぎゃらい'],
    ['Dans la nuit de l\'éternité','どんれにゅーとえたにーと','えいゆうぽろねーず'],
    ['L\'amour et la liberté','らむーるえらりべるて'],
    ['L\'amour et la liberté(譜面変更前)','らむーるえらりべるてふめんへんこうまえ'],
    ['Raison d\'être～交差する宿命～', 'れぞんでーとるこうさするしゅくめい'],
    ['Vulnerability','ヴぁるねらびりてぃ'],
    ['Insane Techniques','いんせいんてくにーくす'],
    ['REINCARNATION','りーいんかーねいしょん','りいんかーねーしょん','トランス'],
    ['Agnus Dei','あにゅすでい'],
    ['Swarm Of Scarabs','すうぉーむおぶすきゃらぶす'],
    ['Tiempo Loco','てぃえんぽろこ'],
    ['Afterimage d\'automne','あふたーいめーじどとんぬ'],
    ['EXUSIA','えくしあ','えくすしあ','いくすしあ','えくすーしあ'],
    ['NITROUS CANNON','にとらすきゃのん','ないとらすきゃのん'],
    ['Grand Chariot','ぐらんしゃりお','ハードアートコア'],
    ['Tizona d\'El Cid','てぃぞなでるしど','てぃそなでるしど','MPB'],
    ['Souhait bleu','すうぇぶるー'],

    // 特殊難読
    ['廿','にじゅういちのまえ'],
    ['Ｘ↑Ｘ↓','てんじょうてんげ'],
    ['Sol Cosine Job 2','即身成仏','そくしんじょうぶつ'],
    ['[ ]DENTITY','あいでんてぃてぃ'],
    ['閃と雷管とロープ','せんとらいかんとろーぷ'],
    ['≡+≡','さんじゅう'],
    ['N.O.', true, 'のヴぁらいくおぶじぇくと'],
    ['405nm (Ryu☆mix)','ふぉーぜろふぁいぶなのめーとる'],
    ['532nm','ふぁいぶすりーつーなのめーとる','ハードコア'],
    ['EXTREME MACH COLLIDER','えくすとりーむまっはこらいだー','えくすとりーむまっはこれだー'],
    ['VOLCANIC BIGBEAT','ヴぉるかにっくびっぐびーと','ヴぉるけにっくびっくびーと'],
    ['X-DEN','皆伝','かいでん'],
    ['.59','天国','てんごく'],
    ['G59','地獄','じごく'],
    ['QQQ','さんきゅー'],
    ['Xlø','くろ'],
    ['ιgniЯRuina','いぐにるいな'],
    ['BLO§OM','ぶろっさむ'],
    ['Ōu Legends','おおうれじぇんず'],
    ['ChaserXX','ちぇいさーえぐぜくす'],
    ['■□模様','くろしろもよう'],
    ['#CMFLG','かもふらーじゅ'],

    // 数字起因
    ['1116','いちいちいちろく'],
    ['Wolf 1061','うるふいちぜろろくいち'],
    ['GRADIUS 2012','ぐらでぃうすにせんじゅうに'],
    ['Nocturnal 2097','のくたーなるとぅえんてぃーないんてぃーせぶん'],
    ['satellite020712 from "CODED ARMS"','さてらいとぜろにぜろなないちにふろむこーでっどあーむず'],
    ['satellite020712 from "CODED ARMS"(譜面変更前)','さてらいとぜろにぜろなないちにふろむこーでっどあーむずふめんへんこうまえ'],
    ['ここからよろしく大作戦143','ここからよろしくだいさくせんわんふぉーすりー'],
    ['100% minimoo-G','ひゃくぱーせんとみにもーぐ'],
    ['10000 MILES AWAY','てんさうざんどまいるずあうぇい'],
    ['ドーナツホール 2024','どーなつほーるにーぜろにーよん'],
    ['Caldwell 99','かるどうぇるないんてぃないん'],

    // 著名ジャンル
    ['neu','のい','ニエンテ'],
    ['uən','いおん','リナシタ'],
    ['音楽','サイレント'],
    ['シュレーディンガーの猫','しゅれーでぃんがーのねこ','トイコンテンポラリー'],
    ['少年は空を辿る','しょうねんはそらをたどる','ムラクモ'],
    ['蛇神','かがち','オリミソ','オリエンタルミソロジー'],
    ['ピアノ協奏曲第１番”蠍火”','ぴあのきょうそうきょくだいいちばんさそりび','ダージュ'],
    ['大見解','だいけんかい','ヒプロ','ヒップロック'],
    ['雪上断火','せつじょうだんか','ヒプロ3','ヒップロック3'],
    ['雫','しずく','ラメント'],
    ['ZETA～素数の世界と超越者～','ぜーたそすうのせかいとちょうえつしゃ','IDM'],
    ['♥LOVE² シュガ→♥','LOVE2 シュガー','ユーロビート'],
    ['CHOCOLATE PHILOSOPHY','ちょこれーとふぃろそふぃー','スウィングワルツ'],
    ['月雪に舞う華のように','げっせつにまうはなのように','つきゆきにまうはなのように','フォレストスノウ'],
    ['Beyond The Earth','びよんどじあーす','コンポラ1','コンテンポラリーネイション'],
    ['サヨナラ・ヘヴン','コンポラ2','コンテンポラリーネイション2'],
    ['The Sky of Sadness','ざすかいおぶさっどねす','コンポラ5','コンテンポラリーネイション5'],
    ['カラルの月','からるのつき','ノマディックネイション'],
    ['少年リップルズ','しょうねんりっぷるず','エモクトロ'],
    ['恋はどう？モロ◎波動OK☆方程式!!','こいはどうもろはどうおーけーほうていしき','理系ポップ'],
    ['凛として咲く花の如く','りんとしてさくはなのごとく','撫子ロック'],
    ['黒髪乱れし修羅となりて','くろかみみだれししゅらとなりて','撫子メタル'],
    ['hora de verdad','おらでべるだ','サイフラ','サイバーフラメンコ'],
    ['シャムシールの舞','しゃむしーるのまい','バトルダンス'],
    ['Blind Justice ～Torn souls, Hurt Faiths ～','ぶらじゃす','ぶらいんどじゃすてぃすとーんそうるずはーとふぇいすず','エピックポエトリー'],
    ['創世ノート','そうせいのーと','クリエイター'],
    ['ƒƒƒƒƒ','ふぉるてししししも','ハードPf'],
    ['Übertreffen','ゆーばーとれっふぇん','プロバロ','プログレッシブバロック'],
    ['No.13','なんばーさーてぃーん','プロバロ','プログレッシブバロック'],
    ['Macuilxochitl','まくいるしょちとる','ピアコン','ピアノコンテンポラリー'],
    ['voltississimo','ぼるてぃっしっしも','VVV'],
    ['BabeL ～Grand Story～','ばべるぐらんどすとーりー','スパステ','スパイラルステアーズ'],
    ['Eine Haube ～聖地の果てにあるもの～','あいねはうべせいちのはてにあるもの','ヴェラム'],
    ['Ergosphere','えるごすふぃあ','亜ジャズ','亜空間ジャズ'],
    ['明鏡止水','めいきょうしすい','禅ジャズ'],
    ['airflow','えあーふろう','えあふろう','インストゥルメンタル'],
    ['朧','おぼろ','ファッシネイション'],
    ['PUNISHER','ぱにっしゃー','ヴァリアントレイヴ'],
    ['天空の夜明け','てんくうのよあけ','アンセム','再生'],
    ['Colors (radio edit)','からーずらじおえでぃっと','トランス'],
    ['Concertino in Blue','こんちぇるてぃのいんぶるー','プログレッシブ'],
    ['V','ぶい','プログレッシブ'],
    ['The Least 100sec','100秒','ざりーすとわんはんどれっとせかんず','プログレッシブ'],
    ['子供の落書き帳','こどものらくがきちょう','プログレ'],
    ['恋愛観測','れんあいかんそく','ハッピーラブゲイザー'],
    ['Remain','りめいん','ルイナススピリチュアル'],
    ['Far east nightbird','ふぁーいーすとないとばーど','ドラムンベース'],
    ['虹色','にじいろ','ラブリートランスポップ'],
    ['Ignited Night','いぐないてっどないと','ヒートアップ'],
    ['RINИE','りんね','シンフォニックセイバー'],
    ['デッドボヲルdeホームラン','でっどぼーるでほーむらん','エレクトリックマヌーシュスウィング'],
    ['Stella Sinistra','すてらしにすとら','シンフォノベーティブロック'],
    ['晴天Bon Voyage','せいてんぼんぼやーじゅ','スウィートロニカ'],
    ['Empathetic','えんぱせてぃっく','ドラムステップ'],
    ['虹色の花','にじいろのはな','ライトビジュアルポップ'],
    ['Synergy For Angels','しなじーふぉーえんじぇるず','オービタリックレボリューション'],
    ['STULTI','すとぅるち','すとぅるてぃ','グラヴィオール'],
    ['轟け！恋のビーンボール！！','とどろけこいのびーんぼーる','ベースボールヒロイン'],
    ['野球の遊び方 そしてその歴史 ～決定版～','やきゅうのあそびかたそしてそのれきしけっていばん','野球のことがよくわかる'],
    ['GAIA','がいあ','スピードダンス'],
    ['お米の美味しい炊き方、そしてお米を食べることによるその効果。','おこめのおいしいたきかたそしておこめをたべることによるそのこうか','お米タル'],
    ['Valanga','ばらんが','アートコア'],
    ['御千手メディテーション','おせんじゅめでぃてーしょん','ニューエイジ合掌コア'],
    ['Votum stellarum','うぉーとぅむすてっらーるむ','ヴぉーたむすてらるむ','アンセムトランス'],
    ['Vinculum stellarum','うぃんくるむすてっらーるむ','うぃんくるむすてらるむ','アンセムトランス'],
    ['Zirkfied','じるくふぁいど','スペレク','スペースレクイエム'],
    ['Idola','いどら','レプリカントコア'],
    ['MOON','むーん','哀愁ユーロ'],
    ['雷君','らいくん','エッジ'],
    ['IMPLANTATION','いんぷらんてーしょん','ゴアトランス'],
    ['LIMIT TOPPA REVOLUTION','りみっととっぱれぼりゅーしょん','ハピコアMAX'],
    ['月光蝶','げっこうちょう','ビジュアル'],
    ['情熱タンデムRUNAWAY','りみっととっぱれぼりゅーしょん','爆走ユーロビート'],
    ['終末を追う者','しゅうまつをおうもの','ジャッジメント'],
    ['繚乱ヒットチャート','りょうらんひっとちゃーと','ネガメロック'],
    ['朱と碧のランページ','あかとあおのらんぺーじ','アニマソング'],
    ['未完成ノ蒸氣驅動乙女','みかんせいのじょうきくどうおとめ','オービタルスチームパンク'],
    ['恋歌疾風！かるたクイーンいろは','こいうたしっぷうかるたくいーんいろは','ハイスピードラブ一首'],
    ['ポチコの幸せな日常','ぽちこのしあわせなにちじょう','わんわんコア'],
    ['100sec. Kitchen Battle!!','わんはんどれっとせこんずきっちんばとる','スペシャルクッキング'], //
    ['321 STARS','すりーつーわんすたーず','テクノポップ'],
    ['レシピのリドル','ガールズティーパーティー'],
    ['マインド・ゲーム','青春剛速球メタル'],
    ['リメンバーリメンバー','レイニーワルツ'],
    ['メイメツ、フラグメンツ','サイバーシンフォニックポップ'],
    ['アルストロメリア','ブルームフュージョン'],
    ['スーパー戦湯ババンバーン','すーぱーせんとうばばんばーん','オンセン♨ヒーロー'],
    ['たまゆら','和風プログレッシブ'],
    ['ラキラキ','ラッキーテクノ'],
    ['FLOWER','ふらわー','トランスコア'],
    ['Foundation of our love','ふぁうんでいしょんおぶあわーらヴ','トランス'],
    ['JET WORLD','じぇっとわーるど','ハードカントリー'],
    ['Jack','じゃっく','ミクスチャー'],
    ['Space Dog','すぺーすどっぐ','ウチュウリョコウ'],
    ['Harmonia','はるもにあ','ニュープレリュード'],
    ['Sorrows','そろうず','そろーず','エモ'],
    ['MANA','まな','スーパースプラッシュチューン'],
    ['SHION','しおん','ハイスピード幻想チューン'],
    ['High School Love','はいすくーるらぶ','ハイスピードラブソング'],
    ['murmur twins','まーまーついんず','カドルコア'],
    ['rumrum triplets','らむらむとりぷれっつ','ラウンジコア'], //
    ['The Sealer ～ア・ミリアとミリアの民～', 'ざしーらーあみりあとみりあのたみ','エレメンタルジグ'],
    ['Linus','らいなす','ラウンジポップ'],
    ['True Blue','とぅるーぶるー','エッセンシャリー'],
    ['The Smile of You','ざすまいるおぶゆー','エレビッツポップ'],
    ['花吹雪 ～ IIDX LIMITED ～','はなふぶきつーでぃーえっくすりみてっど','ジャパニーズオルタレーション'],
    ['白露の風','しらつゆのかぜ','想歌 風'],
    ['梅雪夜','うめゆきよ','想歌 梅'],
    ['LOVE IS ORANGE','らヴいずおれんじ','ハードシャンソン'],
    ['†渚の小悪魔ラヴリィ～レイディオ†(IIDX EDIT)','なぎさのこあくまらヴりぃれいでぃおつーでぃーえっくすえでぃっと','ハイコア'],
    ['quaver♪','くえーばー','くあーばー','ハッピー'],
    ['華爛漫 -Flowers-','はならんまんふらわーず','ハイパージャパネスク2'],
    ['Engraved Mark','えんぐれいヴどまーく','ハッピーサッドコア'],
    ['I\'m so Happy','愛無双','あいむそーはっぴー','ハッピーハードコア'],
    ['HYENA','はいえな','ビッグビート'],
    ['I\'m Screaming LOVE','あいむすくりーみんぐらぶ','テクノポップ'],
    ['ËVOLUTIΦN','えぼりゅーしょん','プラチナムジャパネスク'],
    ['7 Colors','せぶんからーず','プリズムユーロ'],
    ['灼熱Beach Side Bunny','しゃくねつびーちさいどばにー','ブロークンサンバブレイク'],
    ['Triple Counter','とりぷるかうんたー','リスク+バキューム'],
    ['TOXIC VIBRATION','ときしっくヴぁいぶれいしょん','メロディックスピードメタル'],
    ['SigSig','しぐしぐ','マキナ'],
    ['GOLD RUSH','ごーるどらっしゅ','レクリスレイヴ'],
    ['Daily Lunch Special','でいりーらんちすぺしゃる','ラッキーハードコア'],
    ['Daisuke','だいすけ','ユーロビート'],
    ['Mermaid girl','まーめいどがーる','バブルガムダンス'],
    ['mathematical good-bye','ませまてぃかるぐっどばい','ハードコア'],
    ['memories','めもりーず','ビートロック'],
    ['量子の海のリントヴルム','りょうしのうみのりんとヴるむ','エピックプログレ'],
    ['龍と少女とデコヒーレンス','りゅうとしょうじょとでこひーれんす','エピックテクノ'],
    ['海神','わだつみ','ハイドロコア'],
    ['In The Breeze','いんざぶりーず','ハイブリッド'],
    ['RUINA','るいーな','ハードサイスピードコア'],
    ['Realize Maze','りあらいずめいず','ソリチュード'],
    ['妖隠し -あやかしかくし-','ドラムンワルツ'],
    ['打打打打打打打打打打','だだだだだだだだだだ','ジャパニーズトラディショナル'],
    ['perditus†paradisus','ぺるでぃとぅすぱらでぃすす','ぺるでぃたすぱらでぃさす','アンセムコア'],
    ['DIAVOLO','でぃあヴぉろ','トランセンデンタルエチュード'],
    ['Howling','はうりんぐ','ニューレイヴ'],
    ['Element of SPADA','えれめんとおぶすぱーだ','ヒーリングポップ'],
    ['Cleopatrysm','くれおぱとりずむ','ファラオビームステップ'],
    ['KHAMEN BREAK','かーめんぶれいく','プログレッシブゴスペル'],
    ['千年ノ理','せんねんのことわり','ワールドエレクトロニカ'],
    ['Scars of FAUNA','すかーずおぶふぁうな','ワールドエレクトロニカ'],
    ['Second Heaven','セカ天','せかんどへヴん','ハンズアップ'],
    ['Chronoxia','くろのしあ','ワンダークエスト'],
    ['バンブーソード・ガール','J-スピードメタル'],
    ['キャトられ♥恋はモ～モク','きゃとられこいはもーもく','ハイνブリープ'],
    ['ジオメトリック∮ティーパーティー','じおめとりっくてぃーぱーてぃー','カオステイスト'],
    ['パ→ピ→プ→Yeah!','ぱぴぷいぇー','電波ソング'],
    ['バ→ビ→ブ→Bomb!','ばびぶぼむ','電波ソング'],
    ['Sephirot','せふぃろと','トランス'],
    ['Angelic Jelly','えんじぇりっくじぇりー','ハッピーでハードコア'],
    ['StrayedCatz','すとれいどきゃっつ','すとれいきゃっつ','ファンタジー'],
    ['Erosion Mark','えろーじょんまーく','フォーリンアパートコア'],
    ['ZEPHYRANTHES','ぜふぃらんさす','ブルームコア'],
    ['Apocalypse ～dirge of swans～','あぽかりぷすだーじゅおぶすわんず','オラトリオ'],
    ['アストライアの双皿','あすとらいあのそうべい','ゾディアックオラクル7'],
    ['Survival Games','さばいばるげーむず','ウィザウチュナイ-ツヴァイ-'],
    ['Squeeze','すくいーず','ウィザウチュナイ-ゼクス-'],
    ['隅田川夏恋歌','すみだがわかれんか','A.I.デイトポップ'],

    // 略称等
    ['waxing and wanding','わきしんぐあんどわんでぃんぐ'],
    ['QUANTUM TELEPORTATION','くぁんたむてれぽーてーしょん'],
    ['quasar','くえーさー'],
    ['quell～the seventh slave～','くえるざせぶんすすれいヴ','飲食可能第七奴隷'],
    ['LASER CRUSTER','れざくら','れーざーくらすたー'],
    ['BITTER CHOCOLATE STRIKER','びたちょこ','びたーちょこれーとすとらいかー'],
    ['Kung-fu Empire','かんふーえんぱいあ'],
    ['moon_child','むんちゃ','むーんちゃいるど','ポストロック'],
    ['Beyond Evolution','びよえぼ','びよんどえぼりゅーしょん'],
    ['Ancient Scapes','えんすけ','えんしぇんとすけーぷす'],
    ['Bad Encryption','ばどえん','ばっどえんくりぷしょん'],
    ['Bad Maniacs','ばどまに','ばっどまにあっくす'],
    ['GOLDEN CROSS','金十字','ごーるでんくろす'],
    ['Chrono Diver -PENDULUMs-','くろぺん','くろのだいばーぺんでゅらむす'],
    ['超青少年ノ為ノ超多幸ナ超古典的超舞曲','ちょうせいしょうねんのためのちょうたこうなちょうこてんてきちょうぶきょく','ノノナ'],
    ['狂イ咲ケ焔ノ華','くるいざけほむらのはな','イケノ'],
    ['残像ニ繋ガレタ追憶ノHIDEAWAY','ざんぞうにつながれたついおくのはいどあうぇい','ざんぞうにつながれたついおくのはいだうぇい','ニガレタノ'],
    ['Somnidiscotheque','そむにでぃすこてぃーく','夢路歩'],

    // 要検討
    ['夏の匂い。キミの残像。 ft. Kanae Asaba','なつのにおいきみのざんぞうふぃーちゃりんぐかなえあさば'],
    ['水無月の雫 ft. 小林まな','みなづきのしずくふぃーちゃりんぐこばやしまな'],
    ['冬椿 ft. Kanae Asaba','ふゆつばきふぃーちゃりんぐかなえあさば'],
    ['月と夢の跡 ft. マナ','つきとゆめのあとふぃーちゃりんぐまな'],
    ['果たせぬ約束 ft. 小林マナ','はたせぬやくそくふぃーちゃりんぐこばやしまな'],
    ['Blue Bird feat. Kanae Asaba','ぶるーばーどふぃーちゃりんぐかなえあさば'],
    ['Chasing After YOU ～夢の欠片～ ft. 小林マナ','ちぇいしんぐあふたーゆーゆめのかけらふぃーちゃりんぐこばやしまな'],
    ['花冠 feat.Aikapin','はなかんむりふぃーちゃりんぐあいかぴん'],
    ['FLARE -炎舞- ft.Nana Takahashi', 'ふれあえんぶふぃーちゃりんぐななたかはし'],
    ['Get Up! feat. Kanae Asaba','げっとあっぷふぃーちゃりんぐかなえあさば'],
    ['Get set, Go! feat.Kanae Asaba','げっとせっとごーふぃーちゃりんぐかなえあさば'],
    ['Close the World feat.a☆ru','くろーずざわーるどふぃーちゃりんぐある'],
    ['CODE:1 [revision 1.0.1]','こーどわんりびじょんいってんれいてんいち'],
    ['Life Is A Game ft.DD"ナカタ"Metal','らいふいずあげーむふぃーちゃりんぐでぃーでぃーなかためたる'],
    ['LIVE DRIVING!! feat. 花たん','らいぶどらいびんぐふぃーちゃりんぐはなたん'],
    ['PLASMA SOUL NIGHT feat. Nana Takahashi / 709sec.','ぷらずまそうるないとふぃーちゃりんぐななたかはしななまるきゅーせっく'],
    ['セピアの軌跡 ft. 天宮みや(少女フラクタル)','せぴあのきせきふぃーちゃりんぐあまみやみやしょうじょふらくたる'],
    ['COUNTING SHEEP ft. Kanae Asaba','かうんてぃんぐしーぷふぃーちゃりんぐかなえあさば'],
    ['Remedy feat. Kanae Asaba','れめでぃふぃーちゃりんぐかなえあさば'],
    ['Set U Free feat. Kanae Asaba','せっとゆーふりーふぃーちゃりんぐかなえあさば'],
    ['Cranberry City ft. Luschel','くらんべりーしてぃふぃーちゃりんぐらしぇる'],
    ['Ocean Blue feat. Luschel','おーしゃんぶるーふぃーちゃりんぐらしぇる'],
    ['JUST SYNC ft.Kanae Asaba','じゃすとしんくふぃーちゃりんぐかなえあさば'],
    ['Sometimes feat. Kanae Asaba','さむたいむずふぃーちゃりんぐかなえあさば'],
    ['Hands Up feat. kradness BEMANI Sound Team "Sota Fujimori" Remix','はんずあっぷふぃーちゃりんぐくらっどねすびーまにさうんどちーむそうたふじもりりみっくす'],
    ['Breaking Dawn feat. NO+CHIN, AYANO','ぶれいきんぐどーんふぃーちゃりんぐのーちんあやの'],
    ['Don\'t Stop The Music feat. Kanae Asaba','どんとすとっぷざみゅーじっくふぃーちゃりんぐかなえあさば'],
    ['Don\'t Stop The Music feat.森高千里','どんとすとっぷざみゅーじっくふぃーちゃりんぐもりたかちさと'],
    ['Hyper Drive feat. ぷにぷに電機','はいぱーどらいヴふぃーちゃりんぐぷにぷにでんき'],
    ['LAX5 feat.Ryota Yoshinari','らっくすふぁいヴふぃーちゃりんぐよしなりりょうた'],
    ['Stargazing Trip ～星 探す旅～ ft. 小林マナ','すたーげいじんぐとりっぷほしさがすたびふぃーちゃりんぐこばやしまな'],
    ['GENERATE feat.綾倉盟','じぇねれいとふぃーちゃりんぐあやくらめい'],
    ['DISAPPEAR feat. koyomin','でぃさぴあーふぃーちゃりんぐこよみん'],
    ['NRG STAR \'86 feat. 大山愛未','えなじーすたーえいてぃーしっくすふぃーちゃりんぐおおやまあいみ'],
    ['No Limit 2 dAnce feat. 大山愛未','のーりみっととぅーだんすふぃーちゃりんぐおおやまあいみ'],
    ['ROCK女 feat. 大山愛未, Ken','ろっくおんなふぃーちゃりんぐおおやまあいみけん'],
    ['Note Highway ft. KANASA from bless4','のーとはいうぇいふぃーちゃりんぐかなさふろむぶれすふぉー'],
    ['Tell me what you wish feat.らっぷびと','てるみーわっとゆーうぃっしゅふぃーちゃりんぐらっぷびと'],
    ['LIGHTS ft. EVO+','らいつふぃーちゃりんぐえヴぉ'],
    ['Liquid Crystal Girl feat. echo','りきっどくりすたるがーるふぃーちゃりんぐえこー'],
    ['Rave Saves You feat. Cardz (Exclusive IIDX Mix)','れいヴせいヴずゆーふぃーちゃりんぐかーずえくすくるーしヴつーでぃーえっくすみっくす'],
    ['ラクエン Feat.Chiharu Chonan -JAKA respect for K.S.K. Remix','らくえんふぃーちゃりんぐちはるちょうなんじゃかりすぺくとふぉーけーえすけーりみっくす'],
    ['SCREAM THE LIFE FEAT.KYONO','すくりーむざらいふふぃーちゃりんぐきょーの'],
    ['Strong Woman feat.DABO','すとろんぐうーまんふぃーちゃりんぐだぼ'],
    ['This Is Club Muzik feat. 大久保紅葉','でぃすいずくらぶみゅーじっくふぃーちゃりんぐおおくぼもみじ'],
    ['Voltage (feat. Hidemaru)','ヴぉるてーじふぃーちゃりんぐひでまる'],
    ['Winner\'s Proof ft. KANASA from bless4','うぃなーずぷるーふふぃーちゃりんぐかなさふろむぶれすふぉー'],
    ['Wonder Girl feat. Kanae Asaba','わんだーがーるふぃーちゃりんぐかなえあさば'],
    ['do the thing feat. Kanae Asaba','どぅーざしんぐふぃーちゃりんぐかなえあさば'],
    ['elemental bender feat. Kanae Asaba','えれめんたるべんだーふぃーちゃりんぐかなえあさば'],
    ['ハイ*ビスカス ft. Kanae Asaba','はいびすかすふぃーちゃりんぐかなえあさば'],
    ['wanna be a "BAD GIRL" feat. Nana Takahashi','わなびーあばっどがーるふぃーちゃりんぐななたかはし'],
    ['あるビー！ feat.ころねぽち','あるびーふぃーちゃりんぐころねぽち'],
    ['もっと！モット！ときめき feat. 松下','もっとももっとときめきふぃーちゃりんぐまつした'],
    ['愛しくてラヴィンユー ft. マナ','いとしくてらヴぃんゆーふぃーちゃりんぐまな'],
];

// ページ読み込み時に一度だけコンパイル
const compiledSpecials = titleSpecials.map(([pattern, ...rest]) => {
    const replacements = rest[0] === true ? rest.slice(1) : rest;
    const escaped = pattern.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const re = new RegExp('^' + escaped + '(\\([A-Z]\\)|$)');
    return { pattern, replacements, re };
});

const shortSpecialTerms = new Set();
for (const [pattern, ...rest] of titleSpecials) {
    const terms = rest[0] === true ? rest.slice(1) : rest;
    for (const t of terms) {  // patternを除いた読みのみ
        if (typeof t === 'string' && t.trim().length < 2) {
            shortSpecialTerms.add(t.trim());
        }
    }
}

// スペース区切りの各ブロック内でのみ部分一致するか確認する。
// ブロックをまたいだマッチは許可しない。
// （例: "harmonia はるもにあ にゅーぷれ" → ブロック1="harmonia", ブロック2="はるもにあ", ブロック3="にゅーぷれ"）
function matchesInAnyBlock(normStr, noSpaceQuery) {
    if (!noSpaceQuery) return false;
    const blocks = normStr.split(' ');
    for (const block of blocks) {
        const noSpaceBlock = block.replace(/ /g, '');  // blockにスペースはないが念のため
        if (noSpaceBlock.includes(noSpaceQuery)) return true;
    }
    return false;
}

function normalizeForSearch(str, keepSymbols = false, isTitleSide = true) {
    if (!str) return "";
    let s = str;

    // =========================================================
    // 1. タイトル単位の特例（タイトル側のみ）
    //    クエリ側に適用するとパス3のコピペ検索を壊すため除外
    // =========================================================
    if (isTitleSide) {
        for (const { pattern, replacements, re } of compiledSpecials) {
            if (re.test(s)) {
                s = s.replace(pattern, `${pattern} ${replacements.join(' ')}`);
            }
        }
    }

    // =========================================================
    // 2. 1:N 置換（両側に適用）
    // =========================================================
    s = s.replace(/∞/g,  'oo');
    s = s.replace(/∀/g,  'a');
    s = s.replace(/§/g,  'ss');
    s = s.replace(/Æ/g,  'ae');
    s = s.replace(/æ/g,  'ae');

    // =========================================================
    // 3. 1:1 文字置換（両側に適用）
    // =========================================================
    s = s.replace(/ƒ/g, 'f');
    s = s.replace(/[Øø]/g, 'o');
    s = s.replace(/[Üü]/g, 'u');
    s = s.replace(/[Öö]/g, 'o');
    s = s.replace(/[Ää]/g, 'a');
    s = s.replace(/[éèê]/g, 'e');
    s = s.replace(/[àâ]/g, 'a');
    s = s.replace(/û/g, 'u');
    s = s.replace(/ô/g, 'o');
    s = s.replace(/ə/g, 'a');
    s = s.replace(/[Āā]/g, 'a');
    s = s.replace(/[Ōō]/g, 'o');
    s = s.replace(/[Īī]/g, 'i');
    s = s.replace(/Ë/g, 'e');
    s = s.replace(/ã/g, 'a');
    s = s.replace(/í/g, 'i');
    s = s.replace(/¡/g, '!');

    // ギリシャ文字
    s = s.replace(/Λ/g, 'a');
    s = s.replace(/Φ/g, 'o');
    s = s.replace(/Ξ/g, 'e');
    s = s.replace(/β/g, 'b');
    s = s.replace(/ι/g, 'i');
    s = s.replace(/μ/g, 'u');
    s = s.replace(/µ/g, 'u');

    // キリル文字
    s = s.replace(/И/g, 'n');
    s = s.replace(/Ʞ/g, 'k');
    s = s.replace(/Я/g, 'r');

    // 数学・単位記号
    s = s.replace(/×/g, 'x');
    s = s.replace(/℃/g, 'c');
    s = s.replace(/²/g, '2');
    s = s.replace(/@/g, 'a');

    // 漢字    
    s = s.replace(/焱/g, '火');
    s = s.replace(/戀/g, '恋');
    s = s.replace(/腦/g, '脳');
    s = s.replace(/氣/g, '気');
    s = s.replace(/驅/g, '駆');
    s = s.replace(/斃/g, '倒');
    s = s.replace(/華/g, '花');
    s = s.replace(/喪/g, '失');

    // 全角記号 → 半角相当
    s = s.replace(/！/g, '!');
    s = s.replace(/？/g, '?');
    s = s.replace(/～/g, '~');
    s = s.replace(/「/g, '[');
    s = s.replace(/」/g, ']');
    s = s.replace(/（/g, '(');
    s = s.replace(/）/g, ')');

    // =========================================================
    // 4. 記号の削除（keepSymbols=false のときのみ）
    // =========================================================
    if (!keepSymbols) {
        s = s.replace(/[♥♡]/g, '');
        s = s.replace(/∮/g, '');
        s = s.replace(/†/g, ' ');
        s = s.replace(/_/g, '');
        s = s.replace(/[→⇒]/g, '');
        s = s.replace(/[↑↓]/g, '');
        s = s.replace(/[★☆]/g, '');
        s = s.replace(/[《》]/g, '');
        s = s.replace(/[・･]/g, '');
        s = s.replace(/≡/g, '');
        s = s.replace(/[♪♫♨]/g, '');
        s = s.replace(/[◎■□♂〆]/g, '');
        s = s.replace(/…/g, '');
        s = s.replace(/[、,]/g, '');
        s = s.replace(/[。.]/g, '');
        s = s.replace(/[\u201c\u201d]/g, '');
        s = s.replace(/\'/g, '');
        s = s.replace(/[\u207D\u207E\u0B18\u02D9\uA4B3\u0B13]/g, '');
        s = s.replace(/-/g, ' ');
        s = s.replace(/\*/g, '');
        s = s.replace(/:/g,  '');
        s = s.replace(/|/g,  '');
    }

    s = s.replace(/\u00a0/g, ' ');
    s = s.replace(/\u3000/g, ' ');

    // =========================================================
    // 5. 全角英数字 → 半角（一括）
    // =========================================================
    s = s.replace(/[Ａ-Ｚａ-ｚ０-９]/g, c => String.fromCharCode(c.charCodeAt(0) - 0xFEE0));

    // =========================================================
    // 6. 小文字化 + 連続スペース正規化
    // =========================================================
    s = s.toLowerCase();
    s = s.replace(/ +/g, ' ').trim();

    // =========================================================
    // 7. カタカナ→平仮名に統一
    // =========================================================
    s = s.replace(/[\u30A1-\u30F6]/g, c => String.fromCharCode(c.charCodeAt(0) - 0x60));

    // =========================================================
    // 8. 小書き仮名→大文字に統一
    // =========================================================
    s = s.replace(/[ぁぃぅぇぉっゃゅょゎ]/g, c => 'あいうえおつやゆよわ'['ぁぃぅぇぉっゃゅょゎ'.indexOf(c)]);

    // =========================================================
    // 9. 表記揺れ統一
    // =========================================================
    s = s.replace(/ゔあ/g, 'ば');
    s = s.replace(/ゔい/g, 'び');
    s = s.replace(/ゔえ/g, 'べ');
    s = s.replace(/ゔお/g, 'ぼ');
    s = s.replace(/ゔ/g,   'ぶ');
    s = s.replace(/とうー/g, 'つー');
    s = s.replace(/てゆー/g, 'ちゆー');
    s = s.replace(/ですてにー/g, 'ですていにー');
    s = s.replace(/ほらいぞん/g, 'ほらいずん');
    s = s.replace(/けーしよん/g, 'けいしよん');
    s = s.replace(/ねーしよん/g, 'ねいしよん');
    s = s.replace(/れーしよん/g, 'れいしよん');
    s = s.replace(/ういーあー/g, 'ういあ');
    s = s.replace(/れでいー/g, 'れでい');

    return s;
}

function titleMatchesSearch(titleText, searchQuery) {
    if (!searchQuery) return true;

    const trimmed = searchQuery.trim();
    const isShort = trimmed.length < 2;

    if (isShort) {
        const simpleHit = titleText.toLowerCase().includes(trimmed.toLowerCase());
        if (simpleHit) return true;
        if (!shortSpecialTerms.has(trimmed)) return false;
        // 特例語のみ normalizeForSearch パスも追加チェック
        const normQuery = normalizeForSearch(trimmed, false, false);
        const normTitle = normalizeForSearch(titleText, false, true);
        if (normTitle.includes(normQuery)) return true;
        const noSpaceQuery = normQuery.replace(/ /g, '');
        if (noSpaceQuery.length > 0) {
            if (normTitle.replace(/ /g, '').includes(noSpaceQuery)) return true;
            if (matchesInAnyBlock(normTitle, noSpaceQuery)) return true;
        }
        return false;
    }

    const normQuery = normalizeForSearch(searchQuery, false, false);
    const normTitle = normalizeForSearch(titleText,   false, true);
    if (normTitle.includes(normQuery)) return true;

    const noSpaceQuery = normQuery.replace(/ /g, '');
    if (noSpaceQuery.length > 0) {
        if (normTitle.replace(/ /g, '').includes(noSpaceQuery)) return true;
        if (matchesInAnyBlock(normTitle, noSpaceQuery)) return true;
    }

    const keepTitle = normalizeForSearch(titleText,   true, true);
    const keepQuery = normalizeForSearch(searchQuery, true, false);
    if (keepTitle.includes(keepQuery)) return true;

    return false;
}

function cachedTitleMatchesSearch(titleText, searchQuery) {
    if (!searchQuery) return true;

    const trimmed = searchQuery.trim();
    const isShort = trimmed.length < 2;

    if (isShort) {
        const simpleHit = titleText.toLowerCase().includes(trimmed.toLowerCase());
        if (simpleHit) return true;
        if (!shortSpecialTerms.has(trimmed)) return false;
        const cached = window.titleNormCache && window.titleNormCache.get(titleText);
        if (!cached) return titleMatchesSearch(titleText, trimmed);
        const normQuery = normalizeForSearch(trimmed, false, false);
        const noSpaceQ  = normQuery.replace(/ /g, '');
        if (cached.norm.includes(normQuery)) return true;
        if (noSpaceQ.length > 0) {
            if (cached.norm.replace(/ /g, '').includes(noSpaceQ)) return true;
            if (matchesInAnyBlock(cached.norm, noSpaceQ)) return true;
        }
        return false;
    }

    const cached = window.titleNormCache && window.titleNormCache.get(titleText);
    if (!cached) return titleMatchesSearch(titleText, searchQuery);

    const normQuery  = normalizeForSearch(searchQuery, false, false);
    const noSpaceQ   = normQuery.replace(/ /g, '');
    if (cached.norm.includes(normQuery))                                   return true;
    if (noSpaceQ.length > 0) {
        if (cached.norm.replace(/ /g, '').includes(noSpaceQ))             return true;
        if (matchesInAnyBlock(cached.norm, noSpaceQ))                     return true;
    }
    const keepQuery  = normalizeForSearch(searchQuery, true, false);
    if (cached.keep.includes(keepQuery))                                   return true;
    return false;
}